### PR TITLE
Dreamweaver quiz completed

### PR DESCRIPTION
**Pull request by ayan-joshi**
## PR Checklist

This PR is ready for review and it has solved the issue in #5693 
As mentioned in the issue I have completed the dreamweaver quiz , Now All 15 questions of dreamweaver Quiz has been added to the readme with it's answers.

### DOD

- [x] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

Please have a look at my pr I think it's okay @Ebazhanov

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Great job, thank you @ayan-joshi for your contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @ayan-joshi for design, code

**Comment by ayan-joshi** [comment]
> @all-contributors please add @ayan-joshi for design, code

@Ebazhanov Thankss

**Comment by ayan-joshi** [comment]
Is there any swags or surprise for contributing under hacktoberfest @Ebazhanov

**Comment by Ebazhanov** [comment]
https://hacktoberfest.com/participation/

**Pull request merged**
