### PR TITLE
Update python-quiz.md

### PR DESCRIPTION
**Pull request by TSG405**
Added a recent question added in assessment.

Please merge my PR for hacktoberfest 2022 :)

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@TSG405 please resolve merge conflicts, thanks

**Comment by TSG405** [comment]
Hi @Ebazhanov please review and accept the PR now. It is resolved!

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@TSG405 left comment

**Comment by TSG405** [comment]
Please check @Ebazhanov

**Comment by Ebazhanov** [comment]
@all-contributors please add @TSG405 for design, code

**Pull request merged**
