### PR TITLE
Added two new questions and answers

### PR DESCRIPTION
**Pull request by StefanTrpkovic**
Feel free to answer question 79. I think it's D, but not sure.

### CODE REVIEW

**Comment by timh52280** [comment]
I also think the answer is D.

**Comment by Ebazhanov** [comment]
@StefanTrpkovic you can add the answer directly to your PR, if you want

**Comment by StefanTrpkovic** [comment]
I added the answer to the pull request. Thank you

**Review by Ebazhanov — APPROVED** [review]
Looks perfect! Thank you @StefanTrpkovic for your contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @StefanTrpkovic for design, code

**Pull request merged**
