### PR TITLE
add options and answer in  question 172 java

### LINKED ISSUE #6669: JAVA  Q 172 is incomplete
I'm submitting an ISSUE: please check one with "x"
@Ebazhanov 
- [x ] Missed questions/answers 
Q 172 is incomplete 
image
you can check here https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/java/java-quiz.md

can you assign this issue to me

### PR DESCRIPTION
**Pull request by Priyanshuthapliyal2005**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new quiz{'s}
- [x] I have added new reference link{'s}
- [x] I have made small correction/improvements

### Changes / Instructions
closes #6669 

Question 172 (Java): Which of these classes allows us to define our own formatting pattern for dates and time?

 1.SimpleDateFormat
 2.DateTimeFormatter
 3.DateFormat
 4.TimeFormatter
Correct Answer: DateTimeFormatter

THANK YOU

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Looks good, thank you for your contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @Priyanshuthapliyal2005 for design, code

**Comment by Ebazhanov** [comment]
@all-contributors please add @Priyanshuthapliyal2005 for design, code

**Comment by Priyanshuthapliyal2005** [comment]
Thanks @Ebazhanov

**Pull request merged**
