### PR TITLE
Added two new questions for C# skill assessment

### PR DESCRIPTION
**Pull request by aniket414**
IMG_0923
IMG_0924

### CODE REVIEW

**Comment by aniket414** [comment]
@LiviuSosu
@RamonMartinezNieto

**Comment by Vijay-Nirmal** [comment]
image

Add this question as well

**Comment by aniket414** [comment]
> image
> 
> Add this question as well

Will do

**Review by Ebazhanov — APPROVED** [review]
Looks perfect 👍, thank you @aniket414 for your contribution!

**Comment by Ebazhanov** [comment]
@all-contributors please add @aniket414 for design, code

**Pull request merged**
