### PR TITLE
Cleaned duplicates & fixed typos

### PR DESCRIPTION
**Pull request by danie007**
Hi,

- Duplicate questions are removed & numbering is updated
- Fixed spelling errors

Signed-off-by: danie007 <danilselvan@gmail.com>

### CODE REVIEW

**Review by monkrus — CHANGES_REQUESTED** [review]
Daniel, can you please make sure there are no gaps in the text (e.g. between questions and answers)?

**Review by priyanshsheth — APPROVED** [review]

**Review by priyanshsheth — APPROVED** [review]

**Comment by danie007** [comment]
> Daniel, can you please make sure there are no gaps in the text (e.g. between questions and answers)?

@monkrus Thanks for reviewing, however I have not added any lines or modified the formatting. **Could you kindly elaborate on where the gaps are?**

**Review by monkrus — APPROVED** [review]
It seemed to me I saw gaps, but you are perfectly correct.

**Comment by monkrus** [comment]
@all-contributors please add @danie007 for code

**Pull request merged**
