### PR TITLE
Fixed: #2878

### PR DESCRIPTION
**Pull request by masoudk1990**

### CODE REVIEW

**Comment by Ebazhanov** [comment]
> _No description provided._

Thanks for PR @masoudk1990,
Hello, @ethanosullivan can you please review

**Comment by ethanosullivan** [comment]
Hi @Ebazhanov what are you asking me to review specificlly?

**Comment by masoudk1990** [comment]
> 

I Fixed [#2878](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/issues/2878), correct answer is "Stateless".
You can see changes that I made [here](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/2970/commits/7f04990be0220f4e20e81039e60fea48040bdf1e) and [here](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/2970/commits/141e67c0ec7a4d2f6ebe956c05ee2c14c68dd547)

**Comment by ethanosullivan** [comment]
Looks good, thanks.

**Pull request merged**
