### PR TITLE
Update sketchup-quiz.md

### PR DESCRIPTION
**Pull request by gallettube**
Question and answers as much as I can copy.

## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ X] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

I added as much as I can with the info of the test

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Great job @gallettube, thanks a lot! 🍻

**Comment by Ebazhanov** [comment]
@all-contributors please add @gallettube, for design, code

**Comment by Ebazhanov** [comment]
@all-contributors please add @gallettube for design, code

**Comment by gallettube** [comment]
No prob

**Pull request merged**
