### PR TITLE
Added new Flutter Quiz

### PR DESCRIPTION
**Pull request by Miran-Firdausi**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

I added a new flutter quiz file with 20 questions, following the same conventions as other quizzes.

### CODE REVIEW

**Comment by Miran-Firdausi** [comment]
Please accept my pr with label hacktobest-accepted. Any suggestions are welcome.

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@Miran-Firdausi thanks for your PR, can you please share from where you take it, I have checked and there is not such quiz on linkedin. Or?

**Comment by Miran-Firdausi** [comment]
I think I misunderstood it, this is not from linkedin assessment. I thought this repo was to add questions to linkedin.

**Comment by Ebazhanov** [comment]
> I think I misunderstood it, this is not from linkedin assessment. I thought this repo was to add questions to linkedin.

The main idea is collect quizes ONLY from linkedin.

**Comment by Ebazhanov** [comment]
> Understood, I will close the issue.

thanks, anyway great job with PR i really appreciate!!! Have a great evening!

**Comment by Miran-Firdausi** [comment]
You too, man.

**Pull request closed without merging**
