### PR TITLE
updated for instances of the master node

### PR DESCRIPTION
**Pull request by mintuchoudhary**
updated for instances of the master node

### CODE REVIEW

**Comment by mintuchoudhary** [comment]
for reference: https://data-flair.training/blogs/hadoop-high-availability-tutorial/

**Comment by Ebazhanov** [comment]
> for reference: https://data-flair.training/blogs/hadoop-high-availability-tutorial/

@mintuchoudhary thanks your PR if you will add your reference link inside (under the question), it would be even better. Thank you in advance

**Comment by mintuchoudhary** [comment]
@Ebazhanov: Done - Suggestion added. Thanks !

**Review by Ebazhanov — APPROVED** [review]
Looks good to me, thank you for your contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @mintuchoudhary for design, code

**Pull request merged**
