### PR TITLE
added 10 new questions to cybersecurity. Solves #6520

### PR DESCRIPTION
**Pull request by Rohxn16**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

### CODE REVIEW

**Comment by Rohxn16** [comment]
Requesting review @Ebazhanov

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Can you please resolve merge conflicts, thanks

**Comment by Rohxn16** [comment]
@Ebazhanov I have resolved the issue. Idk what is happenning but I have seen the same problem with my previous 2 PR's as well. The order / numberings are becoming inconsistent mid way idk how.

**Review by Ebazhanov — APPROVED** [review]
Great job, thank you @Rohxn16 👍

**Pull request merged**
