### PR TITLE
Update microsoft-word-quiz.md

### PR DESCRIPTION
**Pull request by rradfar**
- Added two questions from the slides provided in issue #1176 . The other two questions were duplicates. The issue can now be closed.

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Thank you, @rradfar, looks good! I will close the issue then! Great job anyway 👍 !

**Comment by samguidewire** [comment]
image

image

**Comment by samguidewire** [comment]
another one : How To Print Document Without Comments Or Markup In Word?

Ans: 
image

**Comment by Ebazhanov** [comment]
@samguidewire thanks, but this issue already closed, we have to create new one! Please let me know if I should help you. Have a good evening!

**Comment by Ebazhanov** [comment]
Ok, FYI added manually directly to master here it is https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/microsoft-word/microsoft-word-quiz.md

**Pull request merged**
