### PR TITLE
Rust new questions

### PR DESCRIPTION
**Pull request by DavidLakeT**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new questions for the Rust quiz.
- [x] I have added new reference links for those questions.

### Changes / Instructions

Questions from Q43 to Q52 have been added in the rust-quiz.md (link references were also added, mainly from Rust Book and Rust by Example documentation).

### CODE REVIEW

**Comment by DavidLakeT** [comment]
This pull request closes issue #5531.

**Comment by DavidLakeT** [comment]
This pull request closes issue #5531

**Comment by DavidLakeT** [comment]
This pull request closes Ebazhanov/linkedin-skill-assessments-quizzes#5531

**Comment by Ebazhanov** [comment]
@all-contributors please add @DavidLakeT for design, code

**Pull request merged**
