### PR TITLE
contributed with helpful link

### PR DESCRIPTION
**Pull request by jivan84**
I'm including a link that discusses Constructor and I hope it will benefit your repository and help your readers learn more about the subject. I hope you will find this worthy. Thank you.

## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ ] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

### CODE REVIEW

**Comment by admhemed** [comment]
Hi @jivan84 
Would you please provide a steps list to how someone can create a new PR?
I created a new branch on my local, but I can't push it. Any guiding please?

**Comment by jivan84** [comment]
Sure i will share some steps through which you can create.

**Comment by jivan84** [comment]
1. Find out the repo in which you want to create the PR.
2. Find the Opportunity in the repo where you want to merge your link or content.
3. After that find README.md file from the top of the repo 
4. Click on that and open the source and find the opportunity where you want to merge in that source 
5. Then write short msg at the bottom of the source and create the pull request 
6. just follow the instructions after that.

**Comment by jivan84** [comment]
Also please do merge my request.

**Review by Ebazhanov — APPROVED** [review]
It is definitely helpful, thank you @jivan84 for your contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @jivan84 for design, code

**Pull request merged**
