### PR TITLE
Added 1 new question C++ (no answer) | Updated C (adding questions, fixing typos)

### PR DESCRIPTION
**Pull request by SABERGLOW**
Added a new question, but I'm not sure about the answer.

P.S: Format was followed.

### CODE REVIEW

**Comment by SABERGLOW** [comment]
Updated c.md . 

Question 23 had 2 typos. "keyword" instead of "keyboard".

**Comment by SABERGLOW** [comment]
3 new questions added in C.md. Answers added too.

**Review by Ebazhanov — APPROVED** [review]
Thank you for new questions and formatting :star: @SABERGLOW, very valuable contribution :exclamation:

**Comment by Ebazhanov** [comment]
@all-contributors please add @SABERGLOW for design, code

**Pull request merged**
