### PR TITLE
Contributed in 13 Files

### PR DESCRIPTION
**Pull request by CS4Usama**
### New questions are added and answered some previous questions in 11 different files.

**My Contributions to some Files are as follows:**

1. Answer & question numbers updated for 16 Files in `README.md`
2. Question # 74 is answered with reference in the `React.js` file.
3. One new question is added (Q60) and trying to answer some previous questions in the `Linux` file. @D4RIO brother please review my answers for Question # 56, 57, 59, 60.
4. Question # 69, 70, 71, 72 are answered in `JSON` file but not confident about question # 70 answer. @iHamzaKhanzada brother please review my answer to Question # 70.
5. Question # 91 is answered in the `CSS` file.
6. Question # 41 and 49 were the same in the `Front-end Development` file. So, I removed question # 49.
7. One new question is added with the answer (Q56) in the `Rest API` file.
8. One new question is added with the answer (Q62) in the `Node.js` file.
9. Question # 56, 57, 61 are answered with reference in the `MongoDB` file.
10. Question # 55, 70, 71 are answered and two new questions are added at the place (Q18 and Q48) in the `Microsoft Word` file. New questions are added at random places because they had some similarities with previous questions, so, I added them after these similar questions. Rest the whole file is similar to before.
11. Five new questions are added in the `IT Operations` file. One image is also added as a reference to question # 24 in the _images_ directory of IT Operations.
12. Question # 40 is answered in the `Microsoft PowerPoint` file. Question # 50 is also answered but not confident about its answer. Question numbering is incorrect after 45, so, I corrected its sequence.

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Hello, @CS4Usama! Amazing job :punch:, thank you for your valuable contribution! :fire: Have a great day!

**Comment by Ebazhanov** [comment]
@all-contributors please add @CS4Usama for design, code

**Comment by CS4Usama** [comment]
Thanks, @Ebazhanov Sir for your valuable appreciations. 🙂

**Comment by brufael** [comment]
> thanks a lot @brufael for the new questions with answers +1 I have added them in codebase already when you have time you can double check if everything looks ok https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/it-operations/it-operations-quiz.md

It's great for me! Now there are many more questions available. I believe most of the questions are here. Amazing!

**Pull request merged**
