### PR TITLE
close a lot of issues

### LINKED ISSUE #5202: Microsoft PowerPoint
image
image

### PR DESCRIPTION
**Pull request by emanuele-em**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new quiz{'s}
- [x] I have added new reference link{'s}
- [x] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Hello, @emanuele-em! Thanks a lot for your valuable contribution! I like it :heart_eyes:
fyi will take care about adding link in Readme for new quiz!!!

**Comment by Ebazhanov** [comment]
actually for Logic-pro i found we already have such folder, I will check if your PR has new questions.

**Comment by emanuele-em** [comment]
> Hello, @emanuele-em! Thanks a lot for your valuable contribution! I like it 😍 fyi will take care about adding link in Readme for new quiz!!!

Excuse my stupidity but I racked my brains for half an hour and didn't understand, what links do you mean?

**Comment by Ebazhanov** [comment]
in your PR, I found new quiz
image

which is already [exist](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/logic-pro/logic-pro-quiz.md), so I have removed it.

answering on your question, the link should be inside the table
image

**Pull request merged**
