### PR TITLE
Added a new question in OOP

### PR DESCRIPTION
**Pull request by Jay206-Programmer**
Added Q82 that I didn't find during my assessment.

#### Q82. What parameters are required to be passed to a class constructor?

- [ ] reference to subclass
- [ ] reference to base class
- [ ] reference to this pointer
- [x] none

Explanation: 
- Here they haven't mentioned any specific language so let's consider all languages.
- References to subclass are never required as you can simply Initialize subclass & use their object.
- References to the base class are not required in Java, Javascript & Python
- While Python & Javascript may require passing _this_ or _self_ in the constructor, It is not passed in Java constructor.
- So _none_ is the answer

### CODE REVIEW

**Comment by Ebazhanov** [comment]
> Added Q82 that I didn't find during my assessment.
> 
> #### Q82. What parameters are required to be passed to a class constructor?
> * [ ]  reference to subclass
> * [ ]  reference to base class
> * [ ]  reference to this pointer
> * [x]  none
> 
> Explanation:
> 
> * Here they haven't mentioned any specific language so let's consider all languages.
> * References to subclass are never required as you can simply Initialize subclass & use their object.
> * References to the base class are not required in Java, Javascript & Python
> * While Python & Javascript may require passing _this_ or _self_ in the constructor, It is not passed in Java constructor.
> * So _none_ is the answer

Hello, @Jay206-Programmer! Thanks for PR, I have tried to add your explanation into the questions, can you please take a look and review my updates, thanks! In general everything look ok, just need you confirmation before I merge it, fyi

**Comment by Jay206-Programmer** [comment]
@Ebazhanov I have verified the comments, it's proper now. 👍

**Review by Ebazhanov — APPROVED** [review]
Thanks again for your contribtuion, great job! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @Jay206-Programmer for design, code

**Comment by Jay206-Programmer** [comment]
> Thanks again for your contribution, great job! 👍

@Ebazhanov you're welcome! :)

**Comment by Ebazhanov** [comment]
> > Thanks again for your contribution, great job! 👍
> 
> @Ebazhanov We are benefitting so much from this repository, I am just giving back to the community! Thanks for maintaining the repo. 👍

you should know the secret, without contributors this repository is nothing 👈

**Pull request merged**
