### PR TITLE
Added questions in Microsoft Azure

### PR DESCRIPTION
**Pull request by neha3423**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new quiz{'s}
- [x] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

I have added new questions in Microsoft Azure along with references.

### CODE REVIEW

**Comment by neha3423** [comment]
@Ebazhanov  please review

**Comment by neha3423** [comment]
@Ebazhanov please review

**Review by Ebazhanov — APPROVED** [review]
Great job, thank you @neha3423 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @neha3423 for design, code

**Pull request merged**
