### PR TITLE
Added 10 new questions to revit. Partially solves #5320

### PR DESCRIPTION
**Pull request by Rohxn16**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@Rohxn16 can you please resolve merge conflicts, thanks!

**Comment by Rohxn16** [comment]
@Ebazhanov how do i exactly do that, this has never happened to me before. Sorry if it is a stupid question.

**Comment by Rohxn16** [comment]
ok nvm my bad, i figured it out. LOL.

**Comment by Ebazhanov** [comment]
currently the last questions in the list https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/revit/revit-quiz.md finished on [Q28](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/revit/revit-quiz.md#q28-what-is-the-benefit-of-buying-revit-through-an-authorized-reseller)

that means your contribution with new questions should starts from 29. and not override already existing one.

**Pull request closed without merging**
