### PR TITLE
Eclipse answers according to Youtube

### PR DESCRIPTION
**Pull request by SimStim**
From your favourite Git noob, with love... ;-)

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @SimStim! Thank you I know it is a lot of typing work behind :muscle:, but can you also add link for this new quiz to Readme.md file? Then I  would be happy to merge your PR! 

thank you in advance!

**Comment by SimStim** [comment]
Umm I have no clue what you're talking about, remember this is the 
second time I use Githut ;-) Maybe you want to copy+paste everything 
into the right places, or maybe you can give me a link to the file I 
should change (and instructions how to change it), I'm willing to do the 
work, I just don't know how...

**Comment by SimStim** [comment]
Good instructions, thank you. I hope it's correct, you did not mention 
if I have to create a pull again, but I just did. Hope I did not change 
the wrong file lol is my specialty ;-)

**Review by Ebazhanov — APPROVED** [review]
@SimStim great job! :muscle:

**Pull request merged**
