### PR TITLE
Fix: #6093

### PR DESCRIPTION
**Pull request by parthasdey2304**
The Issue #6093 of Java Q144 got fixed there where 2 equal options and now this has been changed!!

### CODE REVIEW

**Comment by parthasdey2304** [comment]
Just fixed the issue #6517 with the problem in mysql-quiz.md
Q7 and Q114 - duplicate questions
Q14 and Q90 - duplicate questions
Q100, Q104, Q105 - similar questions

and Q115 is marked with the correct option please merge this!!!

**Comment by parthasdey2304** [comment]
Just solved the issue #6522 please verify this and merge this i have added questions for solidity

**Review by Rohxn16 — APPROVED** [review]
This follows all the rules of the repo and I think is eligible for merging, we need a review from the code owner I suppose.

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @parthasdey2304! Thanks for your PR but I can only accept changes in Java. Solidity is not exist in linkedin, also you removed Mysql

**Comment by parthasdey2304** [comment]
I am sorry, I made a mess I will fix this all.

**Comment by parthasdey2304** [comment]
I am making a fork again and making the changes in Java only..

**Pull request closed without merging**
