### PR TITLE
Added New Python Question

### PR DESCRIPTION
**Pull request by workspace-utkarsh**
Hi, I'm new to open source and wanted to make my contribution by adding new questions in python section for hacktoberfest'22. Kindly consider my PR. Thankyou.

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Thank you @workspace-utkarsh for your PR, can you please resolve merge conflicts. If you need any help pls let me know.

**Comment by workspace-utkarsh** [comment]
Thankyou for assigning me the task. I'm unable to understand the problem @Ebazhanov, when I created the PR there was no merging conflicts. What should I do further please help.

**Comment by Ebazhanov** [comment]
looks like your PR does not contain any changes anymore.

**Comment by workspace-utkarsh** [comment]
I learnt how to solve merge conflicts and I generated a new PR. Kindly assist me if there's anything more I can do. Thankyou.

**Pull request closed without merging**
