### PR TITLE
Update bash-quiz.md to correct formatting

### PR DESCRIPTION
**Pull request by CodeMaster7000**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ ] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [x] I have made small correction/improvements

### CODE REVIEW

**Review by SmashedFrenzy16 — COMMENTED** [review]
@CodeMaster7000, each question is only supposed to have 4 options (judging by what i see on this repository).

**Comment by CodeMaster7000** [comment]
Yes, and it will have 4 options.

**Comment by SmashedFrenzy16** [comment]
Oh yes now I see that you had just changed some existing ones, so they look good to me!

**Review by Ebazhanov — APPROVED** [review]

**Comment by SmashedFrenzy16** [comment]
Yes I know that (I just happened to come across this so I decided to review).

**Comment by CodeMaster7000** [comment]
Sure

**Pull request merged**
