### PR TITLE
Update reactjs-quiz.md

### PR DESCRIPTION
**Pull request by Adi-456**

### CODE REVIEW

**Comment by haxkd** [comment]
@Adi-456 provide proper Description about the PR

**Comment by Adi-456** [comment]
Added few new questions to the react quiz.
Kindly view and merge the PR.

**Review by Ebazhanov — APPROVED** [review]
Looks perfect, thank you @Adi-456 for your contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @Adi-456 for design, code

**Pull request merged**
