### PR TITLE
Fixed options for maven Qn-74 & answered it

### PR DESCRIPTION
**Pull request by c99SRS**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ ] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [x] I have made small correction/improvements

### Changes / Instructions

Added more options to maven Qn-74 and answered it. 
reference site: [Maven Official Doc](https://maven.apache.org/plugins/maven-compiler-plugin/usage.html)

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @c99SRS! Can you please fix merge conflict, thanks

**Comment by c99SRS** [comment]
Hi ,
Yes I will do today evening ist.

**Comment by c99SRS** [comment]
Hi @Ebazhanov I will do this by today evening IST.

**Comment by c99SRS** [comment]
Hi @Ebazhanov I have resolved all the conflicts. Please check it and approve my PR. Thanks!!

**Review by Ebazhanov — APPROVED** [review]
👍

**Pull request merged**
