### PR TITLE
Update jquery-quiz.md

### PR DESCRIPTION
**Pull request by declarck**
Added Questions #79 and #80.

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Hello, @declarck! Thanks a lot for the new questions with answers!!! 👍 Have a great day!

**Comment by Ebazhanov** [comment]
@all-contributors please add @declarck for design, code

**Comment by declarck** [comment]
> Hello, @declarck! Thanks a lot for the new questions with answers!!! 👍 Have a great day!

You're welcome and actually I thank you for this whole project. Perfect work mate, glad I could be of some help.

**Comment by Ebazhanov** [comment]
thanks you too for your contribution, just trying to make this repo attractive, I personally does not have time to do much. Everything now based on contributors, if you want I can add your nickname to the column responsible for Jquery in case if someone will have any question. Please let me know. Have a great day!!!

**Comment by declarck** [comment]
Of course, I would be honored if you would do something like this, and I'll try to help as much as I can if anyone needs to ask a question for _.Net, C#, Front-end dev., HTML, JavaScript, OOP, Python_ or _Photoshop_ besides _JQuery_. Feel free to add me any of them as a consultant for any of these. Have a great day to you too! ^^

**Comment by Ebazhanov** [comment]
thanks for great initiative will add right now 🍺

**Pull request merged**
