### PR TITLE
Update adobe-photoshop-quiz.md

### PR DESCRIPTION
**Pull request by SimStim**
typo

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Warm welcome @SimStim, good find :punch:! Approved :point_left:

**Comment by Ebazhanov** [comment]
@all-contributors please add @SimStim for design, code

**Comment by SimStim** [comment]
> Warm welcome @SimStim, good find 👊! Approved 👈

Thank you, I signed up with github just for this lol hope I did report it the right way!

**Comment by Ebazhanov** [comment]
You reported it like a PRO :muscle:, thanks for the great input! Now your changes will available for everyone! Have a good evening @SimStim!

**Pull request merged**
