### PR TITLE
Added .NET Core quiz

### PR DESCRIPTION
**Pull request by codrrk08**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

### CODE REVIEW

**Comment by codrrk08** [comment]
@Ebazhanov Please verify and approve the PR.

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
we have already such quiz https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/dotnet-framework/dotnet-framework-quiz.md
could you please double check for duplicates and add your new questions, thanks

**Comment by codrrk08** [comment]
Hey @Ebazhanov , Actually the questions in https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/dotnet-framework/dotnet-framework-quiz.md this quiz are .NET framework questions only. The issue #5559 said that there aren't any **.NET Core** questions, for which I have proposed a new quiz. 
I request you to review it again, if there's an issue let me know, I'll do the needful.
Thank You.

**Comment by Ebazhanov** [comment]
> Hey @Ebazhanov , Actually the questions in https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/dotnet-framework/dotnet-framework-quiz.md this quiz are .NET framework questions only. The issue #5559 said that there aren't any **.NET Core** questions, for which I have proposed a new quiz. I request you to review it again, if there's an issue let me know, I'll do the needful. Thank You.

ok, that means your questions is not from https://www.linkedin.com/skill-assessments/hub/quizzes/ right? Because there is no Core version.

**Comment by codrrk08** [comment]
No. These questions are not from linkedIn. I've just added them for practice of the **.NET core framework** concept. 
What would you like me to do? Should I find some questions from LinkedIn based on the same?

**Comment by Ebazhanov** [comment]
> No. These questions are not from linkedIn. I've just added them for practice of the **.NET core framework** concept. What would you like me to do? Should I find some questions from LinkedIn based on the same?

yes, this repo is only for linkedin quizes. Thanks a lot for your time

**Pull request closed without merging**
