### PR TITLE
Agile Methodologies assessment Missing Answer #5828

### PR DESCRIPTION
**Pull request by webdev-ashishk**
# What does this PR do ?
Fixes: #5828 
# Type of change
### Added New Question
Screenshot from 2023-06-11 01-05-05

## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Thank you @webdev-ashishk 👍

**Comment by webdev-ashishk** [comment]
still I am not added  in contribution list why ??

**Comment by Ebazhanov** [comment]
@all-contributors please add @webdev-ashishk for design, code

**Comment by Ebazhanov** [comment]
you should be there https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/README.md

**Pull request merged**
