### PR TITLE
Added Q52 in Aws lambda

### PR DESCRIPTION
**Pull request by chandolakul**
Hi,
Please accept pull request.

Kindly add hacktoberfest-accepted label in this PR.
Added Q52 in Aws lambda

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
merge conflicts

**Comment by chandolakul** [comment]
@Ebazhanov Resolved Conflicts, Please approve the pull request and Kindly add the hacktoberfest-accepted label in this PR.

**Review by Ebazhanov — APPROVED** [review]
LGTM 👍

**Comment by chandolakul** [comment]
@Ebazhanov Kindly add hacktoberfest-accepted label

**Pull request merged**
