### PR TITLE
Update gcp-quiz.md

### PR DESCRIPTION
**Pull request by GTekSD**
I found this 2 questions

### CODE REVIEW

**Comment by manikandan-artium** [comment]
The question number is wrong. it should be 57 and 58.

**Comment by Ebazhanov** [comment]
> The question number is wrong. it should be 57 and 58.

Hello, @manikandan-artium! Thank you for your feedback, I am not an expert to judge but if you could provide reasonable explanation or reference link we can add them directly under the question. 

Regarding this PR i would like to merge it since @GTekSD bring new questions to this repo.

So please create your own PR with improvements and explanation. Thank you in advance!

**Comment by Ebazhanov** [comment]
@all-contributors please add @GTekSD for design, code

**Comment by GTekSD** [comment]
Okay, I am just contributing some questions because i didn't find those questions here.
and I am not sure it answers is correct or not but i got that skill badge. maybe it is correct. 
I just added few questions, please check there answers and update it. I will also try to find out answers with reason from my side..
Thank you everyone.

**Pull request merged**
