### PR TITLE
update for ms outlook

### PR DESCRIPTION
**Pull request by alexbr00ken**
4 new question, and 2 similar (variations) on the old ones but if typing/searching in "find" field during exam, might be better to add them in present form. you decide... thx

### CODE REVIEW

**Comment by alexbr00ken** [comment]
Q7,10,53 questions had 2 selected choices and (hopefully) now it's ok. rest are new questions. all with references. thx

**Review by Ebazhanov — APPROVED** [review]
Looks absolutely perfect! Thank you @alexbr00ken for your contribution 💪

**Comment by alexbr00ken** [comment]
it is the bare minimum I (or any of us) can do... I would like to thank YOU for this entire project. having to visit LinkedIn website every day (every hour) was so stressful until I found your project. keeps me from loosing my mind - and I have learnt a bunch of things - bcs like you said, no point of only copy-pasta the answers. really thx and wish you the best.

**Comment by Ebazhanov** [comment]
thanks for warm words @alexbr00ken, the secret to success is in the contributors 😉

**Pull request merged**
