### PR TITLE
Update javascript-quiz.md

### PR DESCRIPTION
**Pull request by fakhriaunur**
Question 150 What value is assigned to total after this code executes?

## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new quiz{'s}
- [x] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

### CODE REVIEW

**Review by NaNshekhar04 — APPROVED** [review]
LGTM 👍 Ready to get Merged !

**Review by hasanisaeed — APPROVED** [review]

**Review by Ebazhanov — APPROVED** [review]
Thank you @fakhriaunur for the new question with reference, looks perfect! 💯

**Comment by Ebazhanov** [comment]
@all-contributors please add @fakhriaunur for design, code

**Comment by fakhriaunur** [comment]
> 

Cheers! I am glad to help contributing this repo!

**Pull request merged**
