### PR TITLE
Q 39 - 40 [added]

### PR DESCRIPTION
**Pull request by lakshyamcs16**
Added two new questions (39 and 40) that I found in linkedin's Front-end development skill test.

### CODE REVIEW

**Review by vanekbr — APPROVED** [review]
All good ✔️

It also will be nice to have a reference link containing explanation of the issue. Like it is done in [this PR](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/1629/files#diff-7acd4e0f32323f5cbff77cb84cdb289dbd09268e04a1aa3763c2cf453889503aR425). It will help to actually understand the answer rather than just accepting it. For the better future of the industry 🙂

**Review by Ebazhanov — APPROVED** [review]
Great work 👍 , thank you @lakshyamcs16!

**Comment by Ebazhanov** [comment]
> All good ✔️
> 
> It also will be nice to have a reference link containing explanation of the issue. Like it is done in [this PR](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/1629/files#diff-7acd4e0f32323f5cbff77cb84cdb289dbd09268e04a1aa3763c2cf453889503aR425). It will help to actually understand the answer rather than just accepting it. For the better future of the industry 🙂

thanks for collaboration, fully agree with your suggestion!

**Comment by Ebazhanov** [comment]
@all-contributors please add @lakshyamcs16 for design, code

**Pull request merged**
