### PR TITLE
Python utility to convert questions into JSON

### PR DESCRIPTION
**Pull request by ofou**
### Description
This code extracts questions from Markdown files and writes them to JSON files. The code first uses regular expressions to match question blocks in the Markdown files. It then separates the question from the answers and finds the options and correct answers. The code then creates a dictionary for each question that stores the question, options, and correct answers. Finally, the code writes the questions to JSON files.

### Use cases
This code can be used to extract questions from Markdown files for a variety of purposes, such as:

- Creating a quiz or test
- Generating a list of questions for a study guide
- Extracting questions from a textbook or other resource

### Rationale
This code was written to make it easier to extract questions from Markdown files. The code is simple to use and can be run on any Markdown file. The code also produces a JSON file that can be easily imported into other applications.

### Limitations
The code currently only supports a limited subset of Markdown syntax. For example, the code does not support tables or images. The code also does not support multiple choice questions.

### Future work
Future work on this code could include adding support for additional Markdown syntax and question types. The code could also be extended to extract questions from other types of files, or questions.

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @ofou! Great idea, i think it could be really useful, but I would prefer to keep it as utility in separate repo. Could you please move your code under this organisation https://github.com/linkedin-faq

**Comment by ofou** [comment]
I'm not allowed to push to this org. I think it'd be easier to merge using cherry-pick [80a17a8](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/5764/commits/80a17a84111a0c588802738dbbb1da1f7dc7d0db) at any place you think it belongs.

**Comment by Ebazhanov** [comment]
> [ofou](/ofou)

I have invited you to https://github.com/orgs/linkedin-faq/teams/dev-team/members

**Comment by Ebazhanov** [comment]
> I'm not allowed to push to this org. I think it'd be easier to merge using cherry-pick [80a17a8](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/5764/commits/80a17a84111a0c588802738dbbb1da1f7dc7d0db) at any place you think it belongs.

you can add reference to your repo in this [Readme.md](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes)

**Pull request closed without merging**
