### PR TITLE
Answered question Q46 for Adobe Acrobat

### PR DESCRIPTION
**Pull request by margaret-hu**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ ] I have added new quiz{'s}
- [x] I have added new reference link{'s}
- [x] I have made small corrections/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Hello, @margaret-hu! Thank you for your valuable contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @margaret-hu for design, code

**Comment by piyushk77** [comment]
@margaret-hu you have copied the PR #6679 and committed your own. @Ebazhanov Plagiarism must not be accepted at any cost.

**Comment by Ebazhanov** [comment]
> @margaret-hu you have copied the PR #6679 and committed your own. @Ebazhanov Plagiarism must not be accepted at any cost.

you are right, i did not pay attention, sorry

**Pull request merged**
