### PR TITLE
corrected the answer for Python/Q149

### PR DESCRIPTION
**Pull request by alanJames00**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ ] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [x] I have made small correction/improvements

### Changes / Instructions
Corrected the answer for python/Q149 by verifying the answer with executed code.
_Add instructions to me, please type here, thanks_

### CODE REVIEW

**Comment by alanJames00** [comment]
Corrected the answer for Q149 in Python by verifying the executed code

image

**Review by Ebazhanov — APPROVED** [review]
Thank you @alanJames00 for correction 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @alanJames00 for design, code

**Comment by alanJames00** [comment]
@Ebazhanov Hello, I just wanna say thanks for my role

**Pull request merged**
