### PR TITLE
Create kotlin-quiz-pratice.md

### PR DESCRIPTION
**Pull request by sujitpanda**
Hey this is a very good resource. Thanks to all contributors. I have one suggestion. I think it is better to have a practice file where we can practice first instead of opening the file directly where all the answers are pre filled. But yes both the files has to be synced after a new update.

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @sujitpanda! Brilliant Idea, I love it 😍 !!!! yes we have to add new column or make it visible somehow in Readme.md, also your pull request with `kotlin-quiz-pratice.md` looks identical with existing `kotlin-quiz.md` should we keep two files with the same content, does it make sense? Or you are going to create an example with playground?

**Comment by sujitpanda** [comment]
I tried to add a new column but couldn't. I have added the link for the new file in the first column with this PR. 
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/2813 
I will try to add playground example in that file in coming days. Thanks.

**Comment by Ebazhanov** [comment]
@sujitpanda ok 👍 , take your time! Let me know if you need any help!

**Comment by BHARGAVPATEL1244** [comment]
I'll add 35 questions answer in your practice file

**Comment by sujitpanda** [comment]
> I'll add 35 questions answer in your practice file

Don't add answers. Answers are already there in other file. Please add Kotlin Playground link. Please check my last commit. Thanks

**Comment by Ebazhanov** [comment]
Hello, @sujitpanda! Thanks again for your PR, but since there is no any activities I would prefer to close this, feel free to re-open when you finish it! Have great day!

**Pull request closed without merging**
