### PR TITLE
Java_161_Solution

### LINKED ISSUE #6290: Java Q 161
I'm submitting an ISSUE: please check one with "x"

Q161 of java, the options are inappropriate... and the correct answer also

Current file is
- [ ] O(N*N)
- [ ] O(1)
- [x] O(AB)
- [ ] O(A*B)

but it shoud look like 
- [ ] O(N*N)
- [ ] O(1)
- [ ] O(A+B)
- [x] O(A*B)

---------------------------------------------------------------
- [ ] New question{'s} 
- [ ] New assessment 
- [x] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...

### PR DESCRIPTION
**Pull request by Aloneking789**
Fixes #6290
This question aims to rectify inaccuracies in a Java-related programming query by updating both the answer choices and the correct response to reflect proper time complexity representations.

## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ ] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [x] I have made small correction/improvements

### Changes / Instructions

Please add hacktoberfest-accepted label it .Thanks for your merging previous pull request.

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
This questions should be properly formatted and go to this file https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/java/java-quiz.md

**Comment by Aloneking789** [comment]
my Updated_Java_161_Solution.md is visible?

**Comment by Ebazhanov** [comment]
> my Updated_Java_161_Solution.md is visible?

we have file with java questions already https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/java/java-quiz.md, you can add your new question there (if it is not duplicate), thanks

**Comment by Aloneking789** [comment]
can we add any java question?or it should be there in assessment .................... what kinds of more question i can add to the repo

**Comment by Ebazhanov** [comment]
> can we add any java question?or it should be there in assessment .................... what kinds of more question i can add to the repo

you can find related questions from https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/issues
or go to discord channel there https://discord.gg/NKCyjjw3MW there is a lot of new questions

**Pull request closed without merging**
