### PR TITLE
Update html-quiz.md

### PR DESCRIPTION
**Pull request by AirlineDog**
Fixed some questions to match linkedin quiz's.
Added two more questions with answers
Deleted a duplicate question

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@AirlineDog very nice but I want you revert back question 
`#### Q36. What code will produce this table?` because I found that it was not duplication.
Thank you in advance!

**Comment by AirlineDog** [comment]
@Ebazhanov Αre you sure that Q36 is not an incomplete duplicate of Q26, because i can find no difference except that Q36 has 3 answers and Q26 has four.
If you that is not the case here, I will be happy to revert the question back.

**Comment by Ebazhanov** [comment]
> @Ebazhanov Αre you sure that Q36 is not an incomplete duplicate of Q26, because i can find no difference except that Q36 has 3 answers and Q26 has four.
> If you that is not the case here, I will be happy to revert the question back.

Ahh, yes! You are right the questions inside the tests Q26 are similar to Q36 true! Maybe Q36 has new version so, nice catch once again! Could you please fix conflicts, and we can merge your branch! Thank you in advance @AirlineDog!

image

**Comment by AirlineDog** [comment]
@Ebazhanov Conflicts Resolved.

**Review by Ebazhanov — APPROVED** [review]
You are amazingly fast :runner:! Thank you for this contribution! :punch:

**Pull request merged**
