### PR TITLE
Added a new Skill Assessment for iMovie

### LINKED ISSUE #6157: IMovie
I found a new Skill Assessment  IMovie 

I want to add into this repo ;

can you please assign this to me , I am interested to contribute myself in hacktoberfest_23 : );

### PR DESCRIPTION
**Pull request by gupta-soham**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new quiz{'s}
- [x] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

Fixes #6157

### CODE REVIEW

**Comment by gupta-soham** [comment]
I was unsure of the answers to questions Q20 and Q24 and used AI to obtain them.

Also, I have added websites in the beginning which I referred to while creating this assessment.
Please let me know whether it is necessary to mention it.

**Review by Ebazhanov — APPROVED** [review]
Amazing job! 👍 Thanks a lot @gupta-soham for adding new quiz! Also if you can pls add reference link to Readme.md

**Comment by Ebazhanov** [comment]
@all-contributors please add @gupta-soham for design, code

**Comment by gupta-soham** [comment]
> Amazing job! 👍 Thanks a lot @gupta-soham for adding new quiz! Also if you can pls add reference link to Readme.md

I have opened a PR #6429 for the same :)

**Pull request merged**
