### PR TITLE
Update java-quiz.md

### PR DESCRIPTION
**Pull request by Shuklaaa**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

### CODE REVIEW

**Comment by Shuklaaa** [comment]
I have added a new java question based on synchronization

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @Shuklaaa! Can you please resolve merge conflicts, thanks

**Comment by Shuklaaa** [comment]
Done!

**Review by Ebazhanov — APPROVED** [review]
Looks good! Thank you @Shuklaaa 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @Shuklaaa for design, code

**Pull request merged**
