### PR TITLE
update python-quiz.md

### PR DESCRIPTION
**Pull request by amymkchan**
Add Q137

### CODE REVIEW

**Comment by amymkchan** [comment]
Add Question 137

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Thank @amymkchan for your PR, I have double check and I see duplication now, not sure if we need to keep two similar question in the same quiz. What do you think?

**Comment by amymkchan** [comment]
Hi @Ebazhanov, 

This is kind of nice to have…. I’m fine to cancel this request.  Since you’re the owner, I support your final decision.

Have a nice weekend 

Regards,

**Comment by Ebazhanov** [comment]
> Hi @Ebazhanov, This is kind of nice to have…. I’m fine to cancel this request. Since you’re the owner, I support your final decision. Have a nice weekend Regards,
> […](#)
> On 30 Apr 2022, at 3:51 PM, Zhenëk ***@***.***> wrote: ﻿ Assigned #3600 to @amymkchan. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned.

ok, going to close this, but if you still have time please take a look at open issues https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/issues, maybe you can find something. Have a great weekend too! 👍

**Pull request closed without merging**
