### PR TITLE
Added go questions in french

### PR DESCRIPTION
**Pull request by Tanmay-Giram**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ x ] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

Added 10 MCQ in French to go-quiz-fr.md

### CODE REVIEW

**Comment by Tanmay-Giram** [comment]
> @Tanmay-Giram why in french language?
Why not ??? Nobody else is doing it so i thought it would be helpful,  let me know what you think ?.

**Comment by haxkd** [comment]
> > @Tanmay-Giram @haxkd why in french language?
> > Why not ??? Nobody else is doing it so i thought it would be helpful,  let me know what you think ?.

then quiz should be in other languages too??

**Comment by Tanmay-Giram** [comment]
I guess so it's on whoever owns the repo

**Comment by Tanmay-Giram** [comment]
Yeah , I'll keep that in mind

**Comment by haxkd** [comment]
@Ebazhanov what you think?

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @Tanmay-Giram! I think there is no difference between Eng version and your Fr for https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/go/go-quiz.md
pls double check. Thanks

**Pull request closed without merging**
