### PR TITLE
Update eclipse-quiz.md

### PR DESCRIPTION
**Pull request by bilal966**
Issue #1648 Answered Q16 and Q17.

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @bilal966! Sorry for later reply, but can you please help to fix conflicts in you PR, if there is some doubts let's add some reference from official docs! 
thank you in advance! 
image

**Comment by Ebazhanov** [comment]
FYI @bilal966 I am not expert of `eclipse` so can't help in such question

**Comment by Ebazhanov** [comment]
@bilal966 FYI I going to close your PR but feel free to open it in anytime we can merge it! Thanks! 👍

**Comment by bilal966** [comment]
Yes you can close this branch. Someone answered the same questions and that was correct and i agree with that.

**Pull request closed without merging**
