### PR TITLE
Added 101 question but don't know the answer

### PR DESCRIPTION
**Pull request by Aakashvani**
Can anyone help me to find the answer of 101 number question of react assignement

### CODE REVIEW

**Comment by Aakashvani** [comment]
Can anyone help me to find the answer of 101 number question of react assignement

**Comment by Ebazhanov** [comment]
> Can anyone help me to find the answer of 101 number question of react assignement

we can ask @RobTables. Hello Andrew can you pls take a look, thx

**Comment by rahulfaujdar** [comment]
@Aakashvani  @Ebazhanov 
(A) option is correct of 101 number question.

**Comment by Aakashvani** [comment]
@rahulfaujdar can u share any references doc. ?

**Comment by rahulfaujdar** [comment]
@Aakashvani please read this article 

[](https://bobbyhadz.com/blog/react-pass-boolean-as-prop#:~:text=To%20pass%20a%20boolean%20as,be%20wrapped%20in%20curly%20braces.&text=Copied!&text=We%20passed%20a%20bool%20prop%20to%20a%20component.)

and official doc

[](https://reactjs.org/docs/components-and-props.html)

**Comment by Ebazhanov** [comment]
@Aakashvani if you have plan to add answer to your PR, please let me know I can merge it later. thanks

**Comment by Aakashvani** [comment]
> @Aakashvani if you have plan to add answer to your PR, please let me know I can merge it later. thanks

@Ebazhanov yeah, I'll  add the answer  at morning, please wait till then.

**Review by Ebazhanov — APPROVED** [review]
I see your changes, thanks again for your contribution! Well done. 👍 
Have a great day!

**Comment by Ebazhanov** [comment]
@all-contributors please add @Aakashvani for design, code

**Pull request merged**
