### PR TITLE
Update kotlin-quiz.md

### PR DESCRIPTION
**Pull request by ItSNeverLate**
Idiomatic Solution in Kotlin
https://phauer.com/2017/idiomatic-kotlin-best-practices/

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Hello, @ItSNeverLate! Thank you for your contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @ItSNeverLate for design, code

**Comment by ItSNeverLate** [comment]
Hello Ebazhanov

Could I have your Linkedin account address please?

Regards,
Mehdi

**Comment by Ebazhanov** [comment]
@ItSNeverLate I have sent request to you, waiting for approval FYI

**Pull request merged**
