### PR TITLE
add Q101 and modify Q14

### PR DESCRIPTION
**Pull request by MumuTW**
please review the questions modified and the answer as well. thanks!

### CODE REVIEW

**Comment by MumuTW** [comment]
on C++ document. I've added several questions and delete Q70 for duplication. Also slight modification was done on Q14. Please recheck the answer.

**Comment by MumuTW** [comment]
On ML doc. I add Q85 and 86. I also changed the ans of Q82. Please review, thanks!

**Review by Ebazhanov — APPROVED** [review]
Hello, @MumuTW! I saw all your comments, great job! Thank you for your contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @MumuTW for design, code

**Pull request merged**
