### PR TITLE
Update c-quiz.md

### PR DESCRIPTION
**Pull request by VipulDhillon**
added a c question

### CODE REVIEW

**Review by chandolakul — COMMENTED** [review]
Please added this question in c++ file only.

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
merge conflicts

**Comment by Ebazhanov** [comment]
@VipulDhillon ping

**Comment by Ebazhanov** [comment]
@VipulDhillon ping

**Comment by Ebazhanov** [comment]
@VipulDhillon your changes was merged via https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/5084

**Pull request closed without merging**
