### PR TITLE
 #Hacktoberfest Fixed a wrong answer and added a reference

### PR DESCRIPTION
**Pull request by mhaendler**
Hey happy #Hacktoberfest, i stumbled across this repository and found something. 

The Q95 had a wrong answer, as the loop stops at 4 by break and not at 2. (also if you are really clear, the loop stops at 3 by break statement and afterwards increments $i by 1 so the output is 4. But it is what it is.

Also added a reference to Q1 because of the non-strict comparison between numbers and non-numeric strings. As there is a major difference between php version <8.0 and 8.0>.

I also started translating this questions into german, but this is going to take some time.

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Thank you for correction and reference! 
I really appreciate your initiative about translation, but first I would suggest if Linkedin has this translation already, just turn your Languages to DE and see if the question will be in DE accordingly. 
Thanks @mhaendler your for contribution btw 💪

**Comment by Ebazhanov** [comment]
@all-contributors please add @mhaendler for design, code

**Comment by mhaendler** [comment]
> Thank you for correction and reference! I really appreciate your initiative about translation, but first I would suggest if Linkedin has this translation already, just turn your Languages to DE and see if the question will be in DE accordingly. Thanks @mhaendler your for contribution btw 💪

Alright done. I switched the language to "de" and the question's are accordingly then. So there is no translation needed for the questions? As for example in "c++" there is this file: "[c++quiz-de.md](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/c%2B%2B/c%2B%2Bquiz-de.md). Don't we need a similar file for PHP?

**Comment by Ebazhanov** [comment]
@mhaendler it is up to you, any contribution are welcome. I can't control your free time! Have a great day und Ein schönes Wochenende!

**Pull request merged**
