### PR TITLE
Correct the structure of the question

### PR DESCRIPTION
**Pull request by plemanski**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ ] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ X ] I have made small correction/improvements

### Changes / Instructions

The previous question was incorrect and did not make any sense.

### CODE REVIEW

**Review by NaNshekhar04 — APPROVED** [review]
Perfect ! LGTM 👍

**Review by Ebazhanov — APPROVED** [review]
Thank you for correction @plemanski 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @plemanski for design, code

**Comment by Palulu23** [comment]
Can ailesi uçar ailesi

**Pull request merged**
