### PR TITLE
New Question 

### PR DESCRIPTION
**Pull request by dazzle-sah**
@Ebazhanov I have added a new question in Python Section.
If you are merging this PR , then please give it the tag of Hacktoberfest-accepted, as I have contributed this as a part of Hacktoberfest 2022.

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Looks good, but could you please resolve merge conflicts. Thanks @dazzle-sah

**Review by Ebazhanov — APPROVED** [review]
LGTM, thank you @dazzle-sah for your contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @dazzle-sah for design, code

**Comment by dazzle-sah** [comment]
Thankyou so much !

**Pull request merged**
