### PR TITLE
web app 2 alternative link

### PR DESCRIPTION
**Pull request by bandinopla**
I've made an alternative web app to browse the quizzes and complete them. Status displays and progress widgets to freely navigate and see the overall progress.

My app has this repo as a submodule so it feeds from it, taking the markdown and image files.

https://bandinopla.github.io/skill-assessments-quizzes/

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Looks perfect 💯, great job @bandinopla! Can you also share your source code under this organisation https://github.com/linkedin-faq, I already sent you invite, thank you in advance!

**Comment by Ebazhanov** [comment]
@monkrus FYI

**Comment by bandinopla** [comment]
> p.s. you do not need to create new repo, there is some functionality to share it and still keep source code under your account but display in both places.

how would that be?

**Review by bandinopla — COMMENTED** [review]
updated link to point to the new web app location in the linkedin-faq organization

**Review by Ebazhanov — APPROVED** [review]
Well done 💪 , thanks a lot @bandinopla 
Have a great day 🍺

**Pull request merged**
