### PR TITLE
it-operations: removed 2 duplicated questions Q40 and Q66. Fixed Q52 answer. cleaned some typos

### PR DESCRIPTION
**Pull request by malcata**
- Q40 duplicated Q28
- Q66 duplicated Q4

note: the order of the answer options change and that is normal.

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Thanks a lot for your improvements @malcata! 👍 Have a great evening!

**Comment by jpleboeuf** [comment]
Hey, @malcata, I see that you changed the answer for the now Q51 question, "You power up your computer and it starts in Safe Mode. What should you do?", switching from "Restart" to "Determine the cause and address the issue" (which was also my initial choice) - are you sure of the answer because you got it in Practice mode?
Because we had a discussion in #3884 settling the answer of this question to "restart first".
Cheers!

**Comment by Ebazhanov** [comment]
@jpleboeuf do you want me to add you as responsible for some quizes? Please let me know which one you prefer.

**Comment by jpleboeuf** [comment]
Will see later, @Ebazhanov, I still have a huge backlog of fixes to push across many quizzes.
I only noticed this one because I usually quickly check the commit history before starting to write new commits.

However I think that would be a good idea to add a contribution note suggesting contributors to check the open issues related to the quiz they want to contribute to before writing pull requests.

**Pull request merged**
