### PR TITLE
Update html-quiz.md

### PR DESCRIPTION
**Pull request by FarhadAlishov**
I have noticed three new questions that I could partially write down. I saved several screenshots for answers, but not sure how to add them into document.

D
C
B
A

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @FarhadAlishov! Thanks for the cool pull request but before we merge it, let's add your screenshot inside *md file
please use as reference this quiz 
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/master/it-operations/it-operations-quiz.md
What you have to do:
- add folder image inside the quiz folder
- saved screenshot in this folder
- add reference for your screen inside *md file (e.g. `Q12`)

in case you have any questions just ping me 
image

**Comment by FarhadAlishov** [comment]
Hi, @Ebazhanov,

I am not sure I understood the first bullet point correctly. What do you mean by adding a folder image inside quiz folder? Should I create a new folder in 'html' folder, where I can add my images?

**Comment by Ebazhanov** [comment]
> Hi, @Ebazhanov,
> 
> I am not sure I understood the first bullet point correctly. What do you mean by adding a folder image inside quiz folder? Should I create a new folder in 'html' folder, where I can add my images?

yes you are right: 
- quiz folder
  | 
  -  image folder
  -  quiz *md file
  
  just do the same as on example I posted

**Comment by Ebazhanov** [comment]
> Hi, @Ebazhanov,
> 
> I am not sure I understood the first bullet point correctly. What do you mean by adding a folder image inside quiz folder? Should I create a new folder in 'html' folder, where I can add my images?

let me know if you need any help, I can also do it by myself if you don't mind

**Comment by FarhadAlishov** [comment]
Sorry, I've been busy lately. Didn't have time to figure it out. 

Yes, sure, I don't mind if you put images yourself. Basically, all of the pictures are A,B,C,D options for Q84

**Pull request merged**
