### PR TITLE
all questions from all md.s files oragznied in JSON files

### PR DESCRIPTION
**Pull request by zivserphos**
hello friend, first of all i really want to say that im more than appreciate your effort to save this repo as up to date as possible, 
really impressed me!!.

i was searching a good source for restful api to fullStack questions for a big project i am planing to build when I saw this repo that includes so much quality questions on many different subject related.

That's when I decided to take it a step forward and build a script that may help and be usefull for a lot of programmers across the globe

So I converted all of these md quizzes to a well orgnaized json files object array with (query , code? , options , correct answer)

json-files

Each json file looks like this 

React-json-quiz

NodeJs-Json-quiz

I added 4189 valid questions that are more than 90% of all the questions in this repo (unfortunately questions with images included are nout supported yet) organized by subject to _json-quiz/questions folder

statistics

also i kept the script to build the questions in _json-quiz folder , its up to you if want to leave it like that

Importent thing!!! i did not changed any of the files content at all except 4-5 files that i had to rename in order to enable my script be more effective

In my script i used pure javaScript , Lots of array methods and regex.

Looking forward to your response,
Thanks in advance
 Ziv Serpos

### CODE REVIEW

**Comment by ruslanbes** [comment]
Thanks for the idea, but I'd suggest to keep this repo with original `.md` files because they are easier to edit and maintain. If you have a conversion script, it'd be nice to publish it in a separate repository in case someone else wants these questions in `.json`. 

But since it's extra "tooling" it should be separated.

**Comment by Ebazhanov** [comment]
> Thanks for the idea, but I'd suggest to keep this repo with original `.md` files because they are easier to edit and maintain. If you have a conversion script, it'd be nice to publish it in a separate repository in case someone else wants these questions in `.json`.
> 
> But since it's extra "tooling" it should be separated.
> 
> With this tooling you could create a separate repository that will be updated regularly by converting the md->json.

Thanks Ruslan @ruslanbes I totally agree with your comment. FYI @zivserphos we are going to keep only `*.md` files.

**Comment by Ebazhanov** [comment]
@zivserphos thanks again for your idea and this PR, I would like if we can move your idea as separate service to https://github.com/orgs/linkedin-faq/. I have sent you an invite. Going to close this PR for now.

**Comment by zivserphos** [comment]
hey friend i joined the linkedin-faq and  i'm really excited to help in
what ever i can.
can you please give some more details about the purpose of this repo?
thank you very much and have a nice day

‫בתאריך יום א׳, 9 בינו׳ 2022 ב-12:15 מאת ‪Zhenja‬‏ <‪
***@***.***‬‏>:‬

**Comment by Ebazhanov** [comment]
nice thanks for accepting! I see you there, good! 
the idea is to collect some useful resources e.g. https://linkthein.vercel.app

**Comment by zivserphos** [comment]
wow thats so crazy because im actually working about the same project for
my self, i will create a new branch for the repo and start working on it
i'm planning various of features

‫בתאריך יום א׳, 9 בינו׳ 2022 ב-17:40 מאת ‪Zhenja‬‏ <‪
***@***.***‬‏>:‬

**Comment by Ebazhanov** [comment]
@zivserphos do not forget to check this one as well before you start
- https://examopen.com/
- https://github.com/Sharpness-B/linked-practice
- https://wkm97.github.io/md2practice/#/

**Comment by zivserphos** [comment]
so i have been started to working on my project in a separate repo and i
really appreciate  if can help me with some stuff, currently im struggling
with some security issues that github found in my app to be
vulnerability and I still didn't managed to fixed these problems up to this
point,

wonder if you can help me with that, also i would be very happy if you send
me you personal email or we can create a group in slack/discord to
communicate with the team easily

thanks and have a great day

**Comment by Ebazhanov** [comment]
yes for sure, will help 💯 
could you please create an issue so I need some time to understand 
thanks https://github.com/linkedin-faq/linkdin-quizzes/issues

yes you can reach me by email or discord, if you can create slack group please invite me too please, thanks

**Comment by Ebazhanov** [comment]
@zivserphos, send me your email at ebazhanov@yahoo.com
will invite you to the slack

**Pull request closed without merging**
