### PR TITLE
Update aws-lambda-quiz.md

### PR DESCRIPTION
**Pull request by tamanna900**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ ] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [x] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

### CODE REVIEW

**Comment by tamanna900** [comment]
This is give in linkedin skill assessment test

**Review by Ebazhanov — APPROVED** [review]
Hello, @tamanna900! 

Thanks a lot for your contribution! 

👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @tamanna900 for design, code

**Comment by tamanna900** [comment]
I did not clear my LinkedIn skill exam . Please review the post.

**Pull request merged**
