### PR TITLE
Update go-quiz.md

### PR DESCRIPTION
**Pull request by martinyonatann**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

### CODE REVIEW

**Comment by martinyonatann** [comment]
please mark this PR as hacktober @Ebazhanov

**Comment by martinyonatann** [comment]
@Ebazhanov please add tag `hacktoberfest-accepted` if this the PR ok for you, thankyou!

**Review by Ebazhanov — APPROVED** [review]
Thank you @martinyonatann for your PR, great job! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @martinyonatann for design, code

**Pull request merged**
