### PR TITLE
Update microsoft-excel-quiz.md

### PR DESCRIPTION
**Pull request by hyuckjin21**
I find the answer to the question.

### CODE REVIEW

**Comment by cffnascimento** [comment]
WhatsApp Image 2021-10-01 at 10 22 44 AM
WhatsApp Image 2021-10-01 at 10 29 43 AM
WhatsApp Image 2021-10-01 at 10 31 07 AM
WhatsApp Image 2021-10-01 at 10 32 04 AM
WhatsApp Image 2021-10-01 at 10 32 28 AM
WhatsApp Image 2021-10-01 at 10 33 20 AM
WhatsApp Image 2021-10-01 at 10 33 53 AM
WhatsApp Image 2021-10-01 at 10 34 26 AM

**Review by Ebazhanov — APPROVED** [review]
Thank you @hyuckjin21 for adding new answer, looks good! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @hyuckjin21 for code

**Comment by Ebazhanov** [comment]
@cffnascimento thank you for your screenshot I will add all this new questions ASAP, have a great day!

**Pull request merged**
