### PR TITLE
Added  Q176, answer, explanation, refactored code #1

### PR DESCRIPTION
**Pull request by Jirafey**
This question was not in the database, I encountered it today, 
image link: https://ibb.co/B2NY7J9 
explanation source: https://prnt.sc/v3JtSjh-cRiz

## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

No changes were made, I have added explanation, code, 2 refactored versions of the same code so it will be easier to understand by others.

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Thank you @Jirafey for your great input! 💯

**Comment by Ebazhanov** [comment]
@all-contributors please add @Jirafey for design, code

**Comment by Jirafey** [comment]
> Thank you @Jirafey for your great input! 💯

I'll probably give some more I still have some quizzes to go over. Thank you that was my first PR :3

**Comment by owseaman** [comment]
Thanks for sorting it out, good job.

**Pull request merged**
