### PR TITLE
Added new question to AWS

### PR DESCRIPTION
**Pull request by MakendranG**
Added question from Q95 to Q99

### CODE REVIEW

**Comment by MakendranG** [comment]
Hi @Ebazhanov 

This is with reference to the issue https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/issues/4594

I have added the below details in this file.

Added new AWS question from Q95 to Q99

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@MakendranG can we close it, this guy was faster with creating PR sorry. And you also doing great job. Question already in the codebase.

**Comment by MakendranG** [comment]
@Ebazhanov 

You can close this request.  

**Suggestions**

You can mention in Contributors. md as criteria once the issue is assigned to the respective person, and they can work on the issue. Unless assigning the issue, another person shouldn't work. This is one of the best practice.

**Comment by Ebazhanov** [comment]
> @Ebazhanov
> 
> You can close this request.
> 
> **Suggestions**
> 
> You can mention in Contributors. md as criteria once the issue is assigned to the respective person, and they can work on the issue. Unless assigning the issue, another person shouldn't work. This is one of the best practice.

sure, can you please create PR with this update, thank you in advance!

**Pull request closed without merging**
