### PR TITLE
Create LinkedIn-Learning-Certifications-Courses-ExamCertificationsCar…

### PR DESCRIPTION
**Pull request by GTekSD**
…eer Essentials in System Administration by Microsoft and LinkedIn.md

## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

### CODE REVIEW

**Comment by GTekSD** [comment]
new directory for linkedin learning exam answers

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @GTekSD
Is this list of questions from originally Linkedin?

**Comment by GTekSD** [comment]
yes, it from originally Linkedin. have u ever tried to use linked premium, explore more https://www.linkedin.com/learning/

**Comment by Ebazhanov** [comment]
> yes, it from originally Linkedin. have u ever tried to use linked premium, explore more https://www.linkedin.com/learning/

thanks, but i can only accept from here https://www.linkedin.com/skill-assessments/hub/quizzes/
sorry and thanks a lot for your time

**Pull request closed without merging**
