### PR TITLE
Agile Methodologies Solution

### LINKED ISSUE #6115: Agile Methodologies new question
I'm submitting an ISSUE: please check one with "x"

- [X] New question{'s} 
- [ ] New assessment 
- [ ] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [ ] Documentation issue or request for ...
- [ ] ...
AgileMethodologies_new_question

### PR DESCRIPTION
**Pull request by Aloneking789**
Fixes #6115 
This question is about addressing a pattern where certain backlog stories are favored while others are neglected in a Scrum team. It seeks the appropriate action to resolve this issue, emphasizing collaboration and problem-solving within the team.

## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ ] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [X] I have made small corrections/improvements

### Changes / Instructions
I am new to the contributor's community my recent pull request got merged. This encouraged me for more contributions like this!!

### CODE REVIEW

**Comment by Aloneking789** [comment]
can you please add **hacktoberfest-accepted** label to this assessment. My contribution will not be accepted in hacktoberfest if  the label is not there.

**Review by Ebazhanov — APPROVED** [review]
Hello, @Aloneking789! Thank you for your PR, can you pls add question directly to https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/agile-methodologies/agile-methodologies-quiz.md, thanks

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @Aloneking789! Thank you for your PR, can you pls add question directly to https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/agile-methodologies/agile-methodologies-quiz.md, thanks

**Comment by Ebazhanov** [comment]
@Aloneking789 pls close if you are not going to work on it, thanks

**Pull request closed without merging**
