### PR TITLE
Update accounting-quiz.md

### PR DESCRIPTION
**Pull request by QuestionableGuise**
Adding answers

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Thank you @QuestionableGuise for the new answers! 👍  Let me know if you want be added to the contribution list!

**Comment by Ebazhanov** [comment]
@all-contributors please add @QuestionableGuise for design, code

**Review by jesussnavarro — COMMENTED** [review]
Hello, no question of the assignment appears here

**Comment by Ebazhanov** [comment]
@jesussnavarro from my side only suggestion: add explanation (or reference link) to your answers. That will help anyone to better learn concepts they might not have a great understanding about.

**Pull request merged**
