### PR TITLE
Added Quiz,  microsoft-azure-Az-900.md

### PR DESCRIPTION
**Pull request by sudhanshu-77**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [X] I have added new quiz{'s}
- [X] I have added new reference link{'s}
- [X] I have made small correction/improvements

### Changes / Instructions

please consider my contribution  and merge my PR, thanks

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @sudhanshu-77! Can you please look at https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/microsoft-azure/microsoft-azure-quiz.md and check if there is already the same questions (check for duplicates) and update your PR accordingly, thanks

**Comment by sudhanshu-77** [comment]
please review my commits, I have removed all duplicates questions and added  quiz from 72 to 80 at azure quiz.md, Thanks

**Comment by Ebazhanov** [comment]
> https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/microsoft-azure/microsoft-azure-quiz.md

ok, you have to migrate your questions from your separate file into main file https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/microsoft-azure/microsoft-azure-quiz.md

**Comment by sudhanshu-77** [comment]
> > https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/microsoft-azure/microsoft-azure-quiz.md
> 
> ok, you have to migrate your questions from your separate file into main file https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/microsoft-azure/microsoft-azure-quiz.md

Please check I migrate my quiz question from seperate to main file  from question no. 77 to 85

**Comment by Ebazhanov** [comment]
> > > https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/microsoft-azure/microsoft-azure-quiz.md
> > 
> > 
> > ok, you have to migrate your questions from your separate file into main file https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/microsoft-azure/microsoft-azure-quiz.md
> 
> Please check I migrate my quiz question from seperate to main file from question no. 77 to 85

ok, do we still need this file `microsoft-azure/microsoft-azure-Az-900.md` ? if not pls remove it or move questions to the https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/microsoft-azure/microsoft-azure-quiz.md

**Comment by sudhanshu-77** [comment]
Please check I have remove extra file i.e, microsoft-azure/microsoft-azure-Az-900.md , and merge
I migrate my quiz question to main file i.e, microsoft-azure-quiz.md  from question no. 77 to 85

**Review by Ebazhanov — APPROVED** [review]
Great job @sudhanshu-77, thank you for your contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @sudhanshu-77 for design, code

**Pull request merged**
