### PR TITLE
Fix Front-End Development Quiz Q24

### PR DESCRIPTION
**Pull request by adeacetis**
Problem:
Picture with the solution to the question shows up right below the question.

image

Solution: 
Remove the picture below the question.

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @adeacetis 
I am find to remove but do you really see this question without picture, during your tests?
please confirm.

**Comment by adeacetis** [comment]
Hi,

Tested it with `skill-assessments-quizzes` web app. No issue on my end.


image

**Comment by Ebazhanov** [comment]
> Hi,
> 
> Tested it with `skill-assessments-quizzes` web app. No issue on my end. Spacing is insufficient between Question and answer, but this out of scope. It's consistent with the rest of the app.
> 
> image

FYI the App which you are referring is using resource from this repo, of-course there could be some difference. It is better if you will raise a ticket directly to his repository https://github.com/linkedin-faq/skill-assessments-quizzes with question why the picture is not present. Let me know if you need any guide lines. Closing your PR for now

**Comment by adeacetis** [comment]
Thank you. 
We don't need the picture. The picture illustrates the solution. You read the question, then you get the solution and then you can answer.
Beats the concept of Quizz IMO.

**Comment by adeacetis** [comment]
@Ebazhanov: Apologies. There's some misunderstanding. I have edited the main description of this PR with the problem we are facing. 

In the current deployed branch, there's a picture between the question AND the answer. This picture needs to be removed or else I don't understand the concept of Quizzes.

Regards.

**Comment by Ebazhanov** [comment]
ok, thanks let me double check.

**Comment by Ebazhanov** [comment]
@all-contributors please add @adeacetis for design, code

**Pull request merged**
