### PR TITLE
Update t-sql-quiz.md

### PR DESCRIPTION
**Pull request by samiramaleki**
Hi
The #1330 , #1331 ,#1332 corrected

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Amazing, I really appreciate it :grapes:! Thank you, @samiramaleki,  for your valuable contribution! :tulip:

**Comment by Ebazhanov** [comment]
@all-contributors please add @samiramaleki for design, code

**Comment by samiramaleki** [comment]
You're welcome ,
I'm happy😊

**Comment by samiramaleki** [comment]
> Amazing, I really appreciate it 🍇! Thank you, @samiramaleki, for your valuable contribution! 🌷

You're welcome ,
I'm happy😊

**Pull request merged**
