### PR TITLE
Question [18 to 25] added to angularjs-quiz.md

### PR DESCRIPTION
**Pull request by aamita96**
I have added Angular questions and their answer too. All the answers are correct based on my research. Plz, feel free to change it if you find any wrong answer.

**Thanks**

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Wow, you did lot of work, I really appreciate it, thank you @aamita96 for your great input! :rose:

**Comment by Ebazhanov** [comment]
@all-contributors please add @aamita96 for design, code

**Comment by aamita96** [comment]
> Wow, you did lot of work, I really appreciate it, thank you @aamita96 for your great input! 🌹

Thanks, @Ebazhanov for the appreciation. Just need to ask there is still only 15 questions and 2 answers mentioned in the Table of contents for Angularjs as answers for all the questions have already been given. Can someone please update it or is there any particular process to update it?  **Thanks in Advance**

**Comment by Ebazhanov** [comment]
updated, thanks!

**Pull request merged**
