### PR TITLE
Added Reference and Questions (Hacktoberfest)

### PR DESCRIPTION
**Pull request by Itashamodi**
Question 95 had no reference, added reference
reference : https://docs.oracle.com/javase/8/docs/api/java/util/Queue.html

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Could you please double check your PR, there more changes, if you need help please let me know

**Comment by Itashamodi** [comment]
Yes I have checked my PR, there are some other answers too which I added with reference

**Comment by Ebazhanov** [comment]
there is changes for images
image

also merge conflicts

**Comment by Ebazhanov** [comment]
> Yes I have checked my PR, there are some other answers too which I added with reference

What I would like you to check, if you make changes only for Question 95 + reference. There should not be 113 changes displayed in you RP. I think you did something else, pls check.

**Comment by Ebazhanov** [comment]
@Itashamodi i think it is because of the this commit https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4932/commits/cf61dcb651886349fba44321506c5f8c4603ce96

**Pull request closed without merging**
