### PR TITLE
Saharshjain78 patch 1

### PR DESCRIPTION
**Pull request by Saharshjain78**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ ] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
please revert deletion of `CODE_OF_CONDUCT`, thanks

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
there is also merge conflicts

**Comment by Saharshjain78** [comment]
@Ebazhanov  So can you create a new issue for the code of conduct file, so that I can create the new pr.

**Comment by Saharshjain78** [comment]
@Ebazhanov Could you kindly provide me access so that I may make the necessary adjustments to the Code of Conduct file? It appears that I am unable to do so since I do not have permission.

**Comment by Saharshjain78** [comment]
I have created a new PR with no conflicts.

**Pull request closed without merging**
