### PR TITLE
[PR - HACKTOBERFEST] Added tableau questions and answers

### PR DESCRIPTION
**Pull request by dhruman13**
Hi @Ebazhanov! I have added questions and answers of *Tableau* that was previously absent in the repository.
Positively hoping that they will be merged to the repository.

Happy to contribute here and participate in Hacktoberfest 2022!
Thank you!

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Looks amazing, can you also add reference to Readme.md, thank you in advance!

**Comment by Ebazhanov** [comment]
@dhruman13 also can you please send screenshot of any of the question, I can't find this quiz on Linkedin, is it really from Linkedin?

**Comment by dhruman13** [comment]
@Ebazhanov the quiz is not from Linkedin. There were limited question so I merged the questions from different sites that covers almost all topics of Tableau. Thought it would be more helpful.

**Comment by Ebazhanov** [comment]
> @Ebazhanov the quiz is not from Linkedin. There were limited question so I merged the questions from different sites that covers almost all topics of Tableau. Thought it would be more helpful.

thanks and sorry I can accept only quizzes from linkedin. You can maybe organise repo on your own. I think it should be also helpful. Thank you for your PR, once again, if you will have anything related to linkedin you are more then welcome.

**Pull request closed without merging**
