### PR TITLE
updated aws questions

### PR DESCRIPTION
**Pull request by mihai-db**
+4 more questions vs last PR

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @mihai-db! Thank you for your PR, but due to some other PR's merge before your branch has some conflicts please take a look and fix it, if you need help I am here.
image

**Comment by mihai-db** [comment]
> Hello, @mihai-db! Thank you for your PR, but due to some other PR's merge before your branch has some conflicts please take a look and fix it, if you need help I am here.
> image

Thanks and sorry.

**Review by Ebazhanov — APPROVED** [review]
Cool, fix now! Thank you for your contribution! :punch:

**Comment by Ebazhanov** [comment]
@all-contributors please add @mihai-db for code, design

**Pull request merged**
