### PR TITLE
Updating response to `html-quiz.md` and `angular-quiz.md`

### PR DESCRIPTION
**Pull request by hrishikeshps**
Adding answer to "Q84. How will this code render by default in most web browsers?"

### CODE REVIEW

**Comment by hrishikeshps** [comment]
Added response in 'angular-quiz.md'. Let me know if anything else. Thanks.

**Review by Ebazhanov — APPROVED** [review]
Thanks @hrishikeshps for your valuable contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @hridyakrishna for design, code

**Comment by hrishikeshps** [comment]
@Ebazhanov Just a quick query...how can my name be added as a contributor?

**Comment by Ebazhanov** [comment]
oh sorry my bad, made mistake in the name
@all-contributors please add @hrishikeshps for design, code

**Pull request merged**
