### PR TITLE
Updated c++quiz.md

### PR DESCRIPTION
**Pull request by lok84**
Hi @Ebazhanov, @Sneha-Mittal88293, @TSG405 

Contributed a question to C++ linkedin quiz. Will follow up for more!
Please review and accept my PR with hacktoberfest-accepted level 2022! 

Thanks :)

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Looks good, but could you pls solve merge conflicts ...

**Comment by Ebazhanov** [comment]
@lok84 ping

**Comment by lok84** [comment]
check for the PR #4982

**Comment by lok84** [comment]
It can be approved now..

Thanks

**Review by TSG405 — APPROVED** [review]

**Review by TSG405 — APPROVED** [review]

**Comment by Ebazhanov** [comment]
Guys i found there only one change in Codeowners file, I am fine to add new person but there should be reason behind. I would suggest if you will do some reasonable contribution and instead of Codeowners file you will add youself to the main Readme.md table as in Responsible column. Closing this issue for now.

**Comment by lok84** [comment]
True that

**Pull request closed without merging**
