### PR TITLE
Update google-analytics-quiz.md

### PR DESCRIPTION
**Pull request by hmosharrof**

### CODE REVIEW

**Comment by hmosharrof** [comment]
answer 17,18,19,21

**Comment by hmosharrof** [comment]
answer 17,18,19,21

**Review by Ebazhanov — APPROVED** [review]
Thank you, @hmosharrof, for the great input :muscle:  and have a good day!:four_leaf_clover:

**Comment by Ebazhanov** [comment]
@all-contributors please add @hmosharrof for design, code

**Pull request merged**
