### PR TITLE
Update sketchup-quiz.md

### PR DESCRIPTION
**Pull request by Saharshjain78**
I've just completed a contribution to this project by aligning the document with the reference material provided in the issue description. In total, I've made changes to approximately 20 questions, ensuring that they match the content in the reference document. Furthermore, the updated document now includes all 47 questions that were specified in the reference material.

### CODE REVIEW

**Comment by Saharshjain78** [comment]
Hey Ebazhanov, I wanted to know about the progress of the PR, and let me know if there are some changes.

**Review by Ebazhanov — APPROVED** [review]
Amazing work ❤️ , thank you @Saharshjain78 for your valuable contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @Saharshjain78 for design, code

**Comment by Saharshjain78** [comment]
Really glad to contribute to such a useful project!

**Pull request merged**
