### PR TITLE
#Request to add more questions on aws #5689

### LINKED ISSUE #5689: #Request to add more questions on aws
We need more questions on AWS so that it will be easier to get all questions at one place. @jokerkeny  @Amsal1  

The reference which i know is here below:-
https://quizlet.com/340744042/aws-flash-cards/

### PR DESCRIPTION
**Pull request by webdev-ashishk**
# what does this PR do ?
Fixes #5689 

# Type of change
Added 30 quesions to AWS file name aws-quiz-fr.md file
First Question 
q1

Last Question

Screenshot from 2023-05-10 11-04-51

## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
could you please give a reference in Linkedin from where you took this challenge, 
FYI we have already AWS in this repo

**Comment by webdev-ashishk** [comment]
Here I get here information.......
image

**Comment by Ebazhanov** [comment]
> Here I get the information....... image

ok, understand! in this case could you please merge/move your question to some of the existing file (without creating new)
we have 
image

**Comment by webdev-ashishk** [comment]
I deleted my new file and added question in existing file(aws-quiz-fr.md) and updated my PR , Please let me know any changes required ?

**Review by Ebazhanov — APPROVED** [review]
Well done, thank you for so many questions! 👍

**Review by Ebazhanov — APPROVED** [review]
Well done, thank you for so many questions! 👍

**Pull request merged**
