### PR TITLE
Update css-quiz.md

### PR DESCRIPTION
**Pull request by elenderg**
Added some missing questions. This need to be better formatted to fit the document style.

### CODE REVIEW

**Review by Ebazhanov — COMMENTED** [review]
Thanks for your PR 👍  @elenderg, yes it will be good exersice with formatting ))

**Comment by Ebazhanov** [comment]
> Added some missing questions. This need to be better formatted to fit the document style.

sorry for delay I need to find sometime to work on formatting before we merge it, fyi

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@elenderg I did some formatting please take a look, if everything is matched with what you captured, I would be happy to merge. Thank you in advance!

**Comment by elenderg** [comment]
@Ebazhanov Yes it is.

**Review by Ebazhanov — APPROVED** [review]
Thank you @elenderg for your contribution 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @elenderg for design, code

**Pull request merged**
