### PR TITLE
Answer correction and added references to couple of answers!

### PR DESCRIPTION
**Pull request by antra0497**

### CODE REVIEW

**Comment by antra0497** [comment]
Please make it mandatory for people to add references for quality purposes. I took the GCP quiz on LinkedIn and found a wrong answer here!

**Comment by Ebazhanov** [comment]
> Please make it mandatory for people to add references for quality purposes. I took the GCP quiz on LinkedIn and found a wrong answer here!

if we make it mandatory, someone should support owner of PR in case there is not resources. We have `responsible` person in the Readme column and using it from time to time. An other real case when owner of PR is not reacting on my comments (you can see such PR's in the current list) and it will be forever. So it is better to leave it like this with hope someone later will fix it. But I really understand the problem which you want to solver. Thank you for suggestion 👍

**Review by Ebazhanov — APPROVED** [review]
Thank you for the references @antra0497!!!! :bouquet:
if you feel comfortable with GCP questions please add your self to the responsible column in front on this quiz. (in Readme table)
thanks

**Comment by antra0497** [comment]
Hi @Ebazhanov 
Yeah, I saw some people are continuously ghosting you! 😆 
Well, I am comfortable with ML/ Python/ Cloud, and I will keep an eye on GCP! Thanks! 😄

**Comment by Ebazhanov** [comment]
please add yourself to Readme table, I will merge your PR, thanks

**Pull request merged**
