### PR TITLE
Swift question added

### PR DESCRIPTION
**Pull request by GauthamG2**

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Looks good, thank you @GauthamG2 for your contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @GauthamG2 for design, code

**Comment by GauthamG2** [comment]
Awesome, thanks!

**Comment by GauthamG2** [comment]
The PR/MR is still in NOT ACCEPTED state in my Hacktobefest profile. Could
you please check it.

**Comment by Ebazhanov** [comment]
sorry I forgot to apply this label

**Comment by GauthamG2** [comment]
This is still not accepted state. Can you please do something

**Comment by Ebazhanov** [comment]
Hello, Team! This PR was created and merged during **Hacktoberfest** period. @GauthamG2 did a great job, please count his PR as valuable contribution and accept his work. Thanks

**Comment by GauthamG2** [comment]
Thanks for merging the commit. But in the Hacktoberfest profile page, this
PR/MR is still in NOT ACCEPTED state.

**Pull request merged**
