### PR TITLE
Add Adobe XD questions

### PR DESCRIPTION
**Pull request by keerthanak-tw**
#4422 
Adding Adobe XD questions

### CODE REVIEW

**Comment by jdelucca** [comment]
haha, I just also did this one. On question 20, you added the word "all" to the correct answer.

**Comment by keerthanak-tw** [comment]
> haha, I just also did this one. On question 20, you added the word "all" to the correct answer.

Oops. Eagle eyes 👀 😃 
Corrected it ✌️

**Review by Ebazhanov — APPROVED** [review]
Great job! Thanks a lot @keerthanak-tw 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @keerthanak-tw for design, code

**Pull request merged**
