### PR TITLE
Fixes conflict in PR #4589

### PR DESCRIPTION
**Pull request by jdelucca**
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pull/4589 had a minor conflict involving the naming of the questions. I have fixed it for Hacktoberfest.

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
I would prefer we can wait a little bit the answer from the owner of PR. I will ping him once again.

**Review by tripathisharad — COMMENTED** [review]
I have checked everything is looking good

**Review by Ebazhanov — APPROVED** [review]
thanks @jdelucca LGTM

**Review by tripathisharad — COMMENTED** [review]
I have checked everything is ok thank you

**Pull request merged**
