### PR TITLE
Update reactjs-quiz.md

### PR DESCRIPTION
**Pull request by RaviDhoriya**
Marked answer to React test

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@RaviDhoriya thank you for the answer but could you please fix conflicts between your branch and master, then we will can quickly merge your PR.

**Comment by RaviDhoriya** [comment]
Fixed merge conflict

**Comment by RaviDhoriya** [comment]
Fixed merge conflict.

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@RaviDhoriya all good, but right now there is nothing to merge
image
please double-check maybe you still need to push something.
And let me know if you need any help I am here
Have a nice day.

**Comment by RaviDhoriya** [comment]
After I fixed the merge conflict, it seems like that particular answer was already marked. So no need for this pull request at the moment. I'l close this.

Thank you, have a nice day! :)

**Comment by Ebazhanov** [comment]
OK, haha got it, no worries if you're still interesting for contribution but not sure what to do look at the issue, maybe you can find something there. Cheers!
FYI @RaviDhoriya https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/issues

**Pull request closed without merging**
