### PR TITLE
Autodesk Maya questions and answers added

### PR DESCRIPTION
**Pull request by marifoglu**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ x ] I have added new quiz{'s}
- [ x ] I have added new reference link{'s}
- [ x ] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Great job @marifoglu 💯 
Could you also please add reference to the Readme file, before we merge your PR. Thank you in advance!

**Comment by marifoglu** [comment]
Unfortunately, i tried to add maya-quiz.md to the Readme.md but it destroyed all table.

**Review by Ebazhanov — APPROVED** [review]
🔥

**Comment by Ebazhanov** [comment]
@all-contributors please add @marifoglu for design, code

**Pull request merged**
