### PR TITLE
Update windows-server-quiz.md

### PR DESCRIPTION
**Pull request by azrael0learza**
Addition of extra question regarding RADIUS servers, as of 06/07/2021

### CODE REVIEW

**Review by azrael0learza — COMMENTED** [review]
Corrected question formatting.

**Review by Ebazhanov — APPROVED** [review]
nice one 👍 , thank you @azrael0learza 🥇

**Comment by Ebazhanov** [comment]
@all-contributors please add @azrael0learza for design, code

**Comment by calvynlee** [comment]
1 new question:

After installing the active directory domain services role to your windows server 2016 OS, how do you promote the server to a domain controller using the GUI?

Open mmc.exe
Run dcpromo.exe.
Click Add Roles and Features.
Click the notification flag in the Server Manager windows.

**Pull request merged**
