### PR TITLE
Updated mongodb.md and readme.md 

### PR DESCRIPTION
**Pull request by s-faisal**
Updated mongodb.md 
Answered 3 questions which wasn't answered earlier

Updated readme.md 
Updated the count of the mongodb total questions and questions answered.
Added profile in contributers list

### CODE REVIEW

**Comment by s-faisal** [comment]
@Ebazhanov Can you validate this pull request and merge the same?

**Review by Ebazhanov — APPROVED** [review]
Hello, @s-faisal! Thank you for your valuable contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @s-faisal for design, code

**Comment by s-faisal** [comment]
@Ebazhanov 
Thanks for merging the same. :v:

**Pull request merged**
