### PR TITLE
Update adobe-premiere-pro-quiz.md

### PR DESCRIPTION
**Pull request by gallettube**
# PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ ] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [x] I have made small correction/improvements

### Changes / Instructions

https://blog.pond5.com/6248-getting-started-with-video-transitions-and-effects-in-premiere-pro/#:~:text=You%20can%20enable%2Fdisable%20effects,left%20of%20the%20effect%20title.

https://www.premiumbeat.com/blog/audio-automation-in-premiere-pro/#:~:text=Read,affects%20the%20entire%20track%20uniformly.

https://community.adobe.com/t5/premiere-pro-discussions/what-are-the-best-render-settings-for-8-bit-4-2-0-100-mbps-4k-video/td-p/10695910

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@gallettube Can you please add reference links below the answer, thanks

**Comment by Ebazhanov** [comment]
> In the comment of the P.R are the links, right?

yes in your PR message

**Comment by Ebazhanov** [comment]
> I mean there are allready
> 
> First question https://blog.pond5.com/6248-getting-started-with-video-transitions-and-effects-in-premiere-pro/#:~:text=You%20can%20enable%2Fdisable%20effects,left%20of%20the%20effect%20title.
> 
> Second question https://www.premiumbeat.com/blog/audio-automation-in-premiere-pro/#:~:text=Read,affects%20the%20entire%20track%20uniformly.
> 
> Third querstion https://community.adobe.com/t5/premiere-pro-discussions/what-are-the-best-render-settings-for-8-bit-4-2-0-100-mbps-4k-video/td-p/10695910

I mean it would be great if you put inside codebase in *.md file directly, because this PR message with your links will disappear after i merge PR.

**Review by gallettube — COMMENTED** [review]
Added links yo ansers

**Pull request merged**
