### PR TITLE
Added Keynote quiz

### PR DESCRIPTION
**Pull request by auchynnikau**
Added new quiz for Keynote assessment according to #4040 issue.
HACKTOBERFEST

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Thank a lot @auchynnikau, could you also add reference inside Readme file, to make it visible. Thank you

**Comment by auchynnikau** [comment]
> Thank a lot @auchynnikau, could you also add reference inside Readme file, to make it visible. Thank you

Done

**Review by Ebazhanov — APPROVED** [review]
Thanks once again for new topic @auchynnikau, great job!!!! 💪 
could you please also double check if it redirected corrected after it merged. Thanks

**Comment by Ebazhanov** [comment]
@all-contributors please add @auchynnikau for design, code

**Comment by auchynnikau** [comment]
> Thanks once again for new topic @auchynnikau, great job!!!! 💪 could you please also double check if it redirected corrected after it merged. Thanks

Yep, it work's fine)

**Pull request merged**
