### PR TITLE
Update answer for qn. 01

### PR DESCRIPTION
**Pull request by RiyaMathew-11**
I think the correct answer for qn. 1 is the K-means cluster algorithm. The reference was also given in issue #1400. So made the correction.

### CODE REVIEW

**Review by D4RIO — COMMENTED** [review]
Please, would you check Q2? I think you introduced a small change, like a blank space or so.

**Comment by RiyaMathew-11** [comment]
> Please, would you check Q2? I think you introduced a small change, like a blank space or so.

Sure, I would check it out. Thanks for pointing out.

**Comment by RiyaMathew-11** [comment]
> > Please, would you check Q2? I think you introduced a small change, like a blank space or so.
> 
> Sure, I would check it out. Thanks for pointing it out.
It's a small change in whitespace. I've compared with both. It doesn't  show up in the content

**Comment by RiyaMathew-11** [comment]
It's a small change in whitespace. I've compared with both. It doesn't show up in the content

**Review by Ebazhanov — APPROVED** [review]
Well done @RiyaMathew-11 :hibiscus:, thanks for the answer! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @RiyaMathew-11 for code, design

**Pull request merged**
