### PR TITLE
Update java-quiz.md

### PR DESCRIPTION
**Pull request by him2016**

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@him2016 thanks for your PR but could you please resolve merge conflict before we merge it, thanks

**Comment by him2016** [comment]
@Ebazhanov Conflicts resolved. Pls merge. Thanks.

**Review by Ebazhanov — APPROVED** [review]
Looks perfect, thank you @him2016 for your contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @him2016 for design, code

**Pull request merged**
