### PR TITLE
Go Quiz added (17 questions)

### PR DESCRIPTION
**Pull request by ruslanbes**
You can add me as a maintainer for go quiz

### CODE REVIEW

**Comment by monkrus** [comment]
@all-contributors please add @ruslanbes for code

**Comment by monkrus** [comment]
@all-contributors please add @ruslanbes for content

**Comment by Ebazhanov** [comment]
@ruslanbes we were waiting for this contribution very long time, thanks a lot for your PR :punch:, do you have any PET ongoing projects based on Go, where we can make contribute? :blush:

**Comment by ruslanbes** [comment]
@Ebazhanov not. I don't have anything opensource in go that I currently actively develop.

**Pull request merged**
