### PR TITLE
PR for new question in object-oriented-programming-quiz.md

### PR DESCRIPTION
**Pull request by ErShakirAnsari**
Added question #89

### CODE REVIEW

**Comment by ErShakirAnsari** [comment]
image

**Comment by ErShakirAnsari** [comment]
image

**Review by Ebazhanov — APPROVED** [review]
Looks perfect, thank you @ErShakirAnsari for your contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @ErShakirAnsari for design, code

**Pull request merged**
