### PR TITLE
Request to update and change Q62

### PR DESCRIPTION
**Pull request by OskyEdz**
Hi!

I took this quiz and found that Q62 didn't sit quite right with me.
Found this github and am no proposing this change.

I hope you can understand my reasoning to these two changes.

1. I'd like to update the question so that it actually make sense.
2. I'd like to change the answer so it reflects today's view on UEFI

I'v documented both changes in two commits under my fork.
Disregard patch 1 and 2 reference. I thought I made two patches not 2 commits.

### CODE REVIEW

**Comment by 101br03k** [comment]
i agree that the answer is wrong, but is the question different from the linkeding quiz or is it that you want to propose changes to the linkedin quiz. if you want to propose changes to the linkeding quiz i recomend contacting linkedin.

**Review by Ebazhanov — APPROVED** [review]
Thanks a lot for your updated and for your valuable contribution! It is completely fine to do like this. 💯

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
now i understand @OskyEdz, can you maybe put your description under the question? And keep original question to make it searchable?

**Review by OskyEdz — COMMENTED** [review]
Q62. Tania was told to address an issue in the UEFI. How is it accessed?
Was changed to 
Q62. Tania was told to change a setting in the UEFI. How is it accessed?

And the answer changed from
"from the BIOS" to 
"from the computer's startup menu"

The phrase "to adress an issues in UEFI" could be interpreted as to alter something about the UEFI. For example, a employee at Asus found that in some cases your not able to adjust how much voltage the CPU can get, that employees has now been tasked with addressing this issue.

I changed the answer because you would not access the UEFI from the BIOS. Only in rare cases or manufacturing testing experimental stuff, does a system have both UEFI and BIOS.

To get to either UEFI or BIOS on a system you usually go via the computer's boot menu or press a certain key to boot straight into that mode.

**Comment by OskyEdz** [comment]
I'm not sure, but did you have in mind some kind of comment in the MD file?

I'll try that when I'm on my computer tomorrow.

**Comment by OskyEdz** [comment]
@Ebazhanov how do you like this comment?

**Comment by Ebazhanov** [comment]
> @Ebazhanov how do you like this comment?

now looks good, I just got an idea can we have two question original one and one with your correction? Sorry for late reply
this way we can get read this huge comment and keep align with other questions. Or let me know I can change it by myself. Thanks

**Review by Ebazhanov — APPROVED** [review]
Thank you @OskyEdz for your valuable contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @OskyEdz for design, code

**Pull request merged**
