### PR TITLE
Microsoft Excel cleanup

### PR DESCRIPTION
**Pull request by jpleboeuf**
Hello,

here are some fixes for problems I encountered when training with the Microsoft Excel quiz:

In brief:

+ remove Q33, duplicate of Q5;
+ remove Q12, duplicate of Q116 + fix a typo in Q116;
+ remove Q20 (with wrong answer), duplicate of Q105;
+ introduce a "missing screenshot" warning in Q70 & Q71;
+ move Q84 to the Microsoft PowerPoint quiz (unanswered);
+ fix a typo in Q115;
+ remove Q110, duplicate of Q117 + fix a typo in Q117;
+ and finally, automatically renumber questions after last removals.

Pings: @gazihasanrahman & @ckullo.

Hope it helps,
and thanks for this project!

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Thanks a lot @jpleboeuf for your great job 💯 LGTM

**Comment by Ebazhanov** [comment]
@all-contributors please add @jpleboeuf for design, code

**Comment by jpleboeuf** [comment]
Practicing with the LinkedIn-FAQ app, I think there was a problem with the merge, Q110 (now Q106) wasn't removed.
My commit dc5cf6a2df1cad5e089d7750a9f946126925e6a7 was partially merged.

**Comment by Ebazhanov** [comment]
well, good catch because only you can verify it, if you could manage it and push update in one your existing PR we can improve it, thank you in advance! And good night!

**Comment by jpleboeuf** [comment]
Done. see PR #3881.

**Pull request merged**
