### PR TITLE
Updated ruby on rails answers.

### PR DESCRIPTION
**Pull request by vivek-114**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ ] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

Updated few answers.

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Thank you @vivek-114 for your valuable contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @vivek-114 for design, code

**Comment by Bambam320** [comment]
I found a question not included, can I submit a PR to add it?

**Comment by Ebazhanov** [comment]
> I found a question not included, can I submit a PR to add it?

yes please @Bambam320, thank you in advance!

**Pull request merged**
