### PR TITLE
Added New Kotlin questions

### PR DESCRIPTION
**Pull request by sahilgarg90**

### CODE REVIEW

**Review by DFW1N — APPROVED** [review]
Non duplicated questions, correct format thanks for your contribution to Kotlin quizz, I don't have experience with it but im trusting your answers are correct as I lack the experience with Kotlin language.

**Comment by sahilgarg90** [comment]
Thanks for the vote of confidence. I have tested each & every question and after that only I have added them over here.

**Review by Ebazhanov — APPROVED** [review]
Thank you @sahilgarg90 for your valuable contribution! 👍 🥇

**Comment by Ebazhanov** [comment]
@all-contributors please add @sahilgarg90 for design, code

**Pull request merged**
