### PR TITLE
Update rust-quiz.md

### PR DESCRIPTION
**Pull request by palinko91**
I think most of the answers correct. At Q1 both usize as u64 and i32 as i64 feels like a correct answer...

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Thank you @palinko91 for your great input!!!! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @palinko91 for design, code

**Comment by palinko91** [comment]
No problem, I did mine succesfully on Linked In few days ago but sorry I forgot to take notes about the questions, I can only remember there was different ones too. I hope we can gather all the questions and discuss the correct solution for all of them :)

**Comment by Ebazhanov** [comment]
no worries @palinko91 all good!!!! Have a great day!

**Comment by CrabCrabCrabCrab** [comment]
> #### Q2. What do the vertical bars represent here?
> 
> ```rust
> str::thread::spawn(|| {
>     println!("LinkedIn");
> });
> ```
> 
> - [ ] a closure
> - [x] a thread
> - [ ] a future
> - [ ] a block


Are we sure this one is correct? I thought it would be a closure based on the [thread docs](https://doc.rust-lang.org/book/ch16-01-threads.html#creating-a-new-thread-with-spawn) and [closure docs](https://doc.rust-lang.org/book/ch13-01-closures.html#refactoring-with-closures-to-store-code).

I haven't taken the assessment, just passing by.

**Comment by palinko91** [comment]
Yes you are right it has to be fixed for closure.

**Comment by CrabCrabCrabCrab** [comment]
> Yes you are right it has to be fixed for closure.

Just made a PR #3048 for this

**Pull request merged**
