### PR TITLE
Added new python question

### PR DESCRIPTION
**Pull request by MarkFantini**

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@MarkFantini please resolve merge conflicts, thanks

**Comment by MarkFantini** [comment]
@Ebazhanov I'm sorry, but what merge conflict?

**Comment by Ebazhanov** [comment]
> @Ebazhanov I'm sorry, but what merge conflict?

image
you need to google `how to fix merge conflicts` 
let me know if you need anyhelp

**Review by Ebazhanov — APPROVED** [review]
Thank you @MarkFantini for your contribution, LGTM 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @MarkFantini for design, code

**Pull request merged**
