### PR TITLE
Update java-quiz.md

### PR DESCRIPTION
**Pull request by AADILcrackstheweb**
Added 2 new questions.For hacktoberfest22

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@AADILcrackstheweb thanks for new questions, can you please solve merge conflicts.

**Comment by Ebazhanov** [comment]
@AADILcrackstheweb any updates?

**Comment by AADILcrackstheweb** [comment]
done sir
i cleared the conflicts

**Comment by AADILcrackstheweb** [comment]
Thank you for reminding me

**Comment by Ebazhanov** [comment]
oh i see there is no changes.

**Comment by Ebazhanov** [comment]
yes you should looks at already merged PR's here
https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/pulls?q=is%3Apr+is%3Aclosed

**Comment by AADILcrackstheweb** [comment]
Ok sir I will do from next time sir. Thank you somuch sir!

**Pull request closed without merging**
