### PR TITLE
Answer to Q76

### PR DESCRIPTION
**Pull request by shubhanjanmedhi**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [ ] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [x] I have made small correction/improvements

### Changes / Instructions

Answered to  @Q76. Please review @pbachman

### CODE REVIEW

**Comment by pbachman** [comment]
@shubhanjanmedhi looks good for me !

**Review by NaNshekhar04 — APPROVED** [review]
LGTM 👍 Ready to get merged !

**Review by Ebazhanov — APPROVED** [review]
Thank you @shubhanjanmedhi for your contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @shubhanjanmedhi for design, code

**Pull request merged**
