### PR TITLE
Cybersecurity Assessment Linkedin Quizz

### PR DESCRIPTION
**Pull request by DFW1N**
I have added questions from a new quizz on Linkedin, any questions i have not answered is either i am not sure of the answer off the top of my head or am not 100% confident on my answer so i leave it blank will do more research to ensure my answers are correct, in some of my commit messages i embedded some references.

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Thank you for your pull request @DFW1N and new quiz, but could you please fix merge conflicts. Thank you in advance!

**Comment by DFW1N** [comment]
> 
> 
> Thank you for your pull request @DFW1N and new quiz, but could you please fix merge conflicts. Thank you in advance!

Hi Ebazhanov, please review the changes made to resolve the merge conflict current shows there is no conflicts with the base branch.

**Comment by Ebazhanov** [comment]
> > Thank you for your pull request @DFW1N and new quiz, but could you please fix merge conflicts. Thank you in advance!
> 
> Hi Ebazhanov, please review the changes made to resolve the merge conflict current shows there is no conflicts with the base branch.

yes, nicely done @DFW1N, thank you again for your valuable contribution! :muscle:

**Comment by Ebazhanov** [comment]
@all-contributors please add @DFW1N for design, code

**Pull request merged**
