### PR TITLE
Request For Updating Objective-C Assessment Questions #5708

### LINKED ISSUE #5708: Request For Updating Objective-C Assessment Questions
Its been a while since the Objective-C Assessment Questions had been updated. Saw alot of new questions upon taking the assessment. Would greatly appreciate if someone could update the Questions List.

### PR DESCRIPTION
**Pull request by Unknown1934-del**
## PR Checklist

This PR is ready for review and meets the requirements set out
in [Suggestion how to contribute](CONTRIBUTING.md)

### DOD

- [x] I have added new quiz{'s}
- [ ] I have added new reference link{'s}
- [ ] I have made small correction/improvements

### Changes / Instructions

_Add instructions to me, please type here, thanks_

Added 10 Questions

Fixes #5708

### CODE REVIEW

**Review by Unknown1934-del — COMMENTED** [review]
I have added 10 questions. Please review it.

**Review by Ebazhanov — APPROVED** [review]
Thank you @Unknown1934-del for your valuable contribution! Great job 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @Unknown1934-del for design, code

**Comment by Ridzzzz** [comment]
> @all-contributors please add @Unknown1934-del for design, code

Just to quickly point out but Q32 & Q40 have no answers ticked. I dont know if this is worth opening a new issue for.

**Pull request merged**
