### PR TITLE
Added examples and reference links

### PR DESCRIPTION
**Pull request by Aditya-Rajgor**
Python is my favourite language and I learned it from the examples, I have added some examples where needed. I hope it will be helpful for the poeple who are diving into the power of python. Initially, I planned to add questions but all the questions were added already. Anyway, It's hacktoberfest 2021 please mark this pull request as **hacltoberfest-accepted**, but I don't think that would be necessary since topic of the repo has hacktoberfest in it.

Looking forward to contribute more.

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @Aditya-Rajgor! Thanks for PR, could you please fix merge conflicts. Thank you in advance!

**Comment by Aditya-Rajgor** [comment]
Solved ? If now give me bit advice

**Comment by Ebazhanov** [comment]
> Solved ? If now give me bit advice

no there is still some
image

please do once again pull latest changes from master and merge/rebase them with your branch
FYI https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/merging-an-upstream-repository-into-your-fork

pls let me know how it is going

**Comment by Aditya-Rajgor** [comment]
Hey, I saw there were two conflcts left to solve. I just removed those two lines and it worked 👍 Thanks for the information

**Review by Ebazhanov — APPROVED** [review]
Looks perfect 👍 , thank you @Aditya-Rajgor for your valuable contribution!

**Comment by Ebazhanov** [comment]
@all-contributors please add @Nikhil27b for design, code

**Pull request merged**
