### PR TITLE
Update java-quiz.md 

### PR DESCRIPTION
**Pull request by briangor**
Removed the irrelevant images in the java folder and added new questions

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Thank you @briangor for updates and new questions! Great job 💪

**Comment by Ebazhanov** [comment]
@all-contributors please add @briangor for design, code

**Comment by briangor** [comment]
Nice 👌. Does it count in hacktoberfest2022? Possibly a label to the PR

**Comment by Ebazhanov** [comment]
yes sure, I add it by request because not everyone want to have it. fyi

**Comment by briangor** [comment]
Oh cool cool. Thanks 💪

**Pull request merged**
