### PR TITLE
Update accounting-quiz.md

### PR DESCRIPTION
**Pull request by tujinwei**
answer attempted

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Thank you for your answers @tujinwei, looks like you an expert! :muscle:

**Comment by Ebazhanov** [comment]
@all-contributors please add @tujinwei for code, design

**Comment by Ebazhanov** [comment]
@all-contributors please add @tujinwei for code, design

**Comment by tujinwei** [comment]
Thanx @Ebazhanov for adding me and my branch. I tried to finish the task and also get some practice. Might not be 100 percent correct.

**Pull request merged**
