### PR TITLE
Update search-engine-optimization-quiz.md

### PR DESCRIPTION
**Pull request by tripathisharad**
Hi I have added a new seo question please add it with hacktoberfest tag thankyou.

### CODE REVIEW

**Review by GTekSD — CHANGES_REQUESTED** [review]
Explanation

**Review by tripathisharad — COMMENTED** [review]
Hi I have added the solution please merge it thankyou.

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @tripathisharad! I can't find your account, everything is ok? please let me know
https://github.com/tripathisharad
image

**Comment by tripathisharad** [comment]
@Ebazhanov  I dont Know what is happening with my account.

**Comment by tripathisharad** [comment]
@Ebazhanov I am totally unaware about it this is happening first time with me

**Comment by tripathisharad** [comment]
Hi @Ebazhanov thanks for informing I think there was an bug with github now everything is working fine thankyou

**Review by Ebazhanov — APPROVED** [review]
Thank you for the new question and explanation, well done! 💪

**Pull request merged**
