### PR TITLE
Added 4 more React.js questions

### PR DESCRIPTION
**Pull request by harmolipi**
The only question I wasn't 100% sure about was Q81 - so if someone could double check that answer for me, that would be great.

### CODE REVIEW

**Comment by BHARGAVPATEL1244** [comment]
Q.81 answer is right.

**Comment by harmolipi** [comment]
Okay awesome, thanks.

**Review by Ebazhanov — APPROVED** [review]
Thank you @harmolipi for your valuable contribution! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @harmolipi for design, code

**Pull request merged**
