### PR TITLE
Improved javascript Q96

### LINKED ISSUE #3268: Javascript question Q96 seems to be marked the wrong answer.
image
The answer `animals.reverse()` is also wright isn't?

### PR DESCRIPTION
**Pull request by dreking**
Closes #3268

### CODE REVIEW

**Review by Ebazhanov — COMMENTED** [review]
Thank you @dreking for your PR but can you please re-create new one, because I can't see any difference because it looks like you have changed the whole file
image

what I expected to see is the only changes displayed in the tab "File changed" 
changes related to https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/issues/3268 as you mention

right now for some reason the changes affected the whole file

if you need any help pls let me know

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
waiting for reply

**Comment by dreking** [comment]
@Ebazhanov Thanks for the reply. I had some styling conflicts while editing the file which resulted in a format change.
Do you have a default styling settings I can use?

**Comment by Ebazhanov** [comment]
> @Ebazhanov Thanks for the reply. I had some styling conflicts while editing the file which resulted in a format change. Do you have a default styling settings I can use?

got it probably you are talking about prettier, but can you try next approach
- remove `node_modules` if you have installed it
- add you changes
- push without checking with prettier or eslint (but we don't have it)
my idea is to not use any third party check styling and so on

I think you can create new branch

**Comment by dreking** [comment]
Perfect, thanks! Let me create a new PR with a new branch, closing this one

**Pull request closed without merging**
