### PR TITLE
Updated format of 2 questions to show up properly in the markdown

### PR DESCRIPTION
**Pull request by ckvignesh**

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
I really appreciate your contribution, great job @ckvignesh thank you! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @ckvignesh for design, code

**Comment by ckvignesh** [comment]
Thanks for merging this, @Ebazhanov :)

**Review by ckvignesh — COMMENTED** [review]
All good...

**Pull request merged**
