### PR TITLE
New question + checkbox fixes

### PR DESCRIPTION
**Pull request by Gwinbleind**

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Thanks for improvements @Gwinbleind, looks good 👍 !

**Comment by Ebazhanov** [comment]
@all-contributors please add @Gwinbleind for design, code

**Comment by ons-cherif** [comment]
Please correct the answer of this question : Which tag pair is used in HTML to embed JavaScript?
It needs to be <script></script> and NOT <code> !!

**Comment by Ebazhanov** [comment]
@ons-cherif good catch, already updated.
 Thanks for your comment! 👍

**Pull request merged**
