### PR TITLE
Update java-quiz.md

### PR DESCRIPTION
**Pull request by NahianAhmed**
Q4 answer will be 1234. I have run the code and checked.
check here :  https://www.jdoodle.com/iembed/v0/sF5
then run

### CODE REVIEW

**Review by Ebazhanov — APPROVED** [review]
Nice catch! Thank you @NahianAhmed for update! 👍

**Comment by Ebazhanov** [comment]
@all-contributors please add @NahianAhmed for design, code

**Comment by cooldashing24** [comment]
@NahianAhmed your selected answer is correct for your [jdoodle](https://www.jdoodle.com/iembed/v0/sF5) link as it uses the `length` property of an array.
Screenshot from 2022-06-28 11-01-03

---

But the actual question uses the `size()` method, and that is not valid.
Screenshot from 2022-06-28 11-01-14

@Ebazhanov please ignore this change

**Comment by Ebazhanov** [comment]
@cooldashing24 thanks for your message will revert it back, all good!

**Comment by NahianAhmed** [comment]
@Ebazhanov sorry. i miss that. @cooldashing24 thanks man! 👍

**Comment by Ebazhanov** [comment]
no worries all good, team work!

**Pull request merged**
