### PR TITLE
Add what is Github 

### PR DESCRIPTION
**Pull request by Sneha-Mittal88293**

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
please resolve merge conflicts, thanks

**Comment by Sneha-Mittal88293** [comment]
please check one's again i resolve the merge conflict

**Review by Ebazhanov — APPROVED** [review]
Thank you @Sneha-Mittal88293, looks good! 👍 
Have a great day!

**Comment by Sneha-Mittal88293** [comment]
Thank you..😁

**Pull request merged**
