### PR TITLE
logic_pro assesment questionns

### PR DESCRIPTION
**Pull request by VINAYBOYAT11**

### CODE REVIEW

**Comment by VINAYBOYAT11** [comment]
@Ebazhanov  please check out my pull request..

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@VINAYBOYAT11 thanks for screesnhot they could go to issues, inside the repo we keep only text. Can you please raise an issue with your screenshots, someone can transfer it to text. And close this PR, thanks

**Comment by VINAYBOYAT11** [comment]
heyy @Ebazhanov i created this issues cam you please attached hactober tag

**Comment by Ebazhanov** [comment]
since issue https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/issues/4631 was created I am closing this PR

**Pull request closed without merging**
